// Code generated by qtc from "comment_editnreview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/admin/comment_editnreview.qtpl:1
package admin

//line views/admin/comment_editnreview.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/admin/comment_editnreview.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/admin/comment_editnreview.qtpl:1
func (p *CommentEdit) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/admin/comment_editnreview.qtpl:1
	qw422016.N().S(`

<div class="index">
    `)
//line views/admin/comment_editnreview.qtpl:4
	if p.PageName == "admin_comment_review" && len(p.DefaultComment.Content) == 0 {
//line views/admin/comment_editnreview.qtpl:4
		qw422016.N().S(`
        <h1>没有 `)
//line views/admin/comment_editnreview.qtpl:5
		qw422016.E().S(p.Title)
//line views/admin/comment_editnreview.qtpl:5
		qw422016.N().S(`</h1>
    `)
//line views/admin/comment_editnreview.qtpl:6
	} else {
//line views/admin/comment_editnreview.qtpl:6
		qw422016.N().S(`
    <h1>`)
//line views/admin/comment_editnreview.qtpl:7
		qw422016.E().S(p.Title)
//line views/admin/comment_editnreview.qtpl:7
		qw422016.N().S(`</h1>
    <p><a href="/t/`)
//line views/admin/comment_editnreview.qtpl:8
		qw422016.N().DUL(p.DefaultTopic.ID)
//line views/admin/comment_editnreview.qtpl:8
		qw422016.N().S(`" target="_blank">`)
//line views/admin/comment_editnreview.qtpl:8
		qw422016.E().S(p.DefaultTopic.Title)
//line views/admin/comment_editnreview.qtpl:8
		qw422016.N().S(`</a></p>
    <p>by `)
//line views/admin/comment_editnreview.qtpl:9
		qw422016.E().S(p.DefaultComment.Name)
//line views/admin/comment_editnreview.qtpl:9
		qw422016.N().S(` at `)
//line views/admin/comment_editnreview.qtpl:9
		qw422016.E().S(p.DefaultComment.AddTimeFmt)
//line views/admin/comment_editnreview.qtpl:9
		qw422016.N().S(`</p>
    <form class="pure-form" action="" method="post" onsubmit="form_post(); return false;">
        <div>
            <fieldset class="pure-group">
                <textarea id="id-content" class="pure-input-1 topic-con-input" placeholder="* 内容">`)
//line views/admin/comment_editnreview.qtpl:13
		qw422016.N().S(p.DefaultComment.Content)
//line views/admin/comment_editnreview.qtpl:13
		qw422016.N().S(`</textarea>
            </fieldset>
            <div id="id-msg"></div>
            <div class="fleft pure-button-group">
                <input id="btn-preview" type="button" value="预览" name="submit" onclick="previewComment(); return false;" class="pure-button button-success" />
                <input id="btn-submit" type="submit" value="发表" name="submit" onclick="submitComment(); return false;" class="pure-button pure-button-primary" />
                <input id="fileUpload" type="file" accept="image/*,video/*,audio/*" onChange="uploadFile()" class="pure-button" name="fileUpload" style="font-size: .8334em;width: 95px;" />
                <button id="insert-break" type="button" class="pure-button">插入分割线</button>
                `)
//line views/admin/comment_editnreview.qtpl:21
		if p.PageName == "admin_comment_review" {
//line views/admin/comment_editnreview.qtpl:21
			qw422016.N().S(`
                <a href="?act=del" class="pure-button button-warning fr">直接删除</a>
                `)
//line views/admin/comment_editnreview.qtpl:23
		}
//line views/admin/comment_editnreview.qtpl:23
		qw422016.N().S(`
            </div>
            <div class="c"></div>

            <div id="id-preview" class="markdown-body entry-content"></div>
        </div>
    </form>

    <script>
        let btnReviewEle = document.getElementById("btn-preview");
        let conEle = document.getElementById("id-content");
        var msgEle = document.getElementById("id-msg");
        var reviewEle = document.getElementById("id-preview");

        document.getElementById("insert-break").addEventListener('click', function (event) {
            let break_line = "\n`)
//line views/admin/comment_editnreview.qtpl:38
		qw422016.N().S(p.ReadMoreBreak)
//line views/admin/comment_editnreview.qtpl:38
		qw422016.N().S(`\n";
            let pos = conEle.selectionStart;
            let con = conEle.value;
            conEle.value = con.slice(0, pos) + break_line + con.slice(pos);
        }, false);

        function previewComment() {
            var con = conEle.value.trim();
            if (con === "") {
                conEle.focus();
                return
            }
            postAjax("/content/preview", JSON.stringify({Act: "commentPreview", Content: con}), function(data){
                var obj = JSON.parse(data)
                //console.log(obj);
                if(obj.Code === 200) {
                    msgEle.style.display = "none";
                    reviewEle.innerHTML = obj.Html;
                    reviewEle.style.display = "block";
                }else{
                    reviewEle.innerHTML = "";
                    reviewEle.style.display = "none";
                    msgEle.innerText = obj.Msg;
                }
            });
        }

        function submitComment() {
            var con = conEle.value.trim();
            if (con === "") {
                conEle.focus();
                return
            }
            postAjax("/admin/comment/edit", JSON.stringify({"ID": `)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().DUL(p.DefaultComment.ID)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().S(`, "TopicId": `)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().DUL(p.DefaultComment.TopicId)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().S(`, "ReplyId": `)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().DUL(p.DefaultComment.ReplyId)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().S(`, "Content": con, "UserId": `)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().DUL(p.DefaultComment.UserId)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().S(`, "AddTime": `)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().DL(p.DefaultComment.AddTime)
//line views/admin/comment_editnreview.qtpl:71
		qw422016.N().S(`}), function(data){
                var obj = JSON.parse(data)
                msgEle.innerText = obj.Msg;
                conEle.focus();
                conEle.value = "";
                toReplyId = 0;
                if(obj.Code === 200) {
                    `)
//line views/admin/comment_editnreview.qtpl:78
		if p.GoBack {
//line views/admin/comment_editnreview.qtpl:78
			qw422016.N().S(`
                    window.location.href = "/t/`)
//line views/admin/comment_editnreview.qtpl:79
			qw422016.N().DUL(p.DefaultComment.TopicId)
//line views/admin/comment_editnreview.qtpl:79
			qw422016.N().S(`#r`)
//line views/admin/comment_editnreview.qtpl:79
			qw422016.N().DUL(p.DefaultComment.ID)
//line views/admin/comment_editnreview.qtpl:79
			qw422016.N().S(`";
                    return false;
                    `)
//line views/admin/comment_editnreview.qtpl:81
		}
//line views/admin/comment_editnreview.qtpl:81
		qw422016.N().S(`
                    `)
//line views/admin/comment_editnreview.qtpl:82
		if p.PageName == "admin_comment_review" {
//line views/admin/comment_editnreview.qtpl:82
			qw422016.N().S(`
                    window.location.href = "/admin/comment/review";
                    `)
//line views/admin/comment_editnreview.qtpl:84
		} else {
//line views/admin/comment_editnreview.qtpl:84
			qw422016.N().S(`
                    if(data.Tid > 0){
                        window.location.href = "/t/"+data.Tid;
                    }else{
                        window.location.href = "/admin/my/comment";
                    }
                    `)
//line views/admin/comment_editnreview.qtpl:90
		}
//line views/admin/comment_editnreview.qtpl:90
		qw422016.N().S(`
                    return false;
                } else if (obj.Code === 201) {
                    window.location.href = "/member/`)
//line views/admin/comment_editnreview.qtpl:93
		qw422016.N().DUL(p.CurrentUser.ID)
//line views/admin/comment_editnreview.qtpl:93
		qw422016.N().S(`?type=comment";
                    return false;
                }
                reviewEle.style.display = "none";
                msgEle.style.display = "block";
            });
        }

        document.addEventListener('paste', function (evt) {
            var url = "/file/upload";
            var items = evt.clipboardData && evt.clipboardData.items;
            var file = null;
            if(items && items.length) {
                for(var i=0; i!==items.length; i++) {
                    var iType = items[i].type;
                    if(iType.indexOf('image') !== -1 || iType.indexOf('video') !== -1 || iType.indexOf('audio') !== -1) {
                        file = items[i].getAsFile();
                        if(!!!file) {
                            continue;
                        }

                        // upload file object.
                        var form = new FormData();
                        form.append('file', file);

                        postAjax("/file/upload", form, function(data){
                            let obj = JSON.parse(data)
                            //console.log(obj);
                            if(obj.Code === 200) {
                                let img_url = "\n" + s2tag(obj.Url, `)
//line views/admin/comment_editnreview.qtpl:122
		qw422016.E().V(p.SiteCf.AutoDecodeMp4)
//line views/admin/comment_editnreview.qtpl:122
		qw422016.N().S(`) + "\n";
                                let pos = conEle.selectionStart;
                                let con = conEle.value;
                                conEle.value = con.slice(0, pos) + img_url + con.slice(pos);
                            }else{
                                console.warn(obj.Msg);
                            }
                        });
                    }
                }
            }
        });
        function uploadFile() {
            let form = new FormData();
            form.append("file", fileUpload.files[0]);
            postAjax("/file/upload", form, function(data){
                let obj = JSON.parse(data)
                if(obj.Code === 200) {
                    let img_url = "\n" + s2tag(obj.Url, `)
//line views/admin/comment_editnreview.qtpl:140
		qw422016.E().V(p.SiteCf.AutoDecodeMp4)
//line views/admin/comment_editnreview.qtpl:140
		qw422016.N().S(`) + "\n";
                    let pos = conEle.selectionStart;
                    let con = conEle.value;
                    conEle.value = con.slice(0, pos) + img_url + con.slice(pos);
                }else{
                    console.warn(obj.Msg);
                }
            });
        }
    </script>

    `)
//line views/admin/comment_editnreview.qtpl:151
	}
//line views/admin/comment_editnreview.qtpl:151
	qw422016.N().S(`

</div>

`)
//line views/admin/comment_editnreview.qtpl:155
}

//line views/admin/comment_editnreview.qtpl:155
func (p *CommentEdit) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/admin/comment_editnreview.qtpl:155
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/admin/comment_editnreview.qtpl:155
	p.StreamMainBody(qw422016)
//line views/admin/comment_editnreview.qtpl:155
	qt422016.ReleaseWriter(qw422016)
//line views/admin/comment_editnreview.qtpl:155
}

//line views/admin/comment_editnreview.qtpl:155
func (p *CommentEdit) MainBody() string {
//line views/admin/comment_editnreview.qtpl:155
	qb422016 := qt422016.AcquireByteBuffer()
//line views/admin/comment_editnreview.qtpl:155
	p.WriteMainBody(qb422016)
//line views/admin/comment_editnreview.qtpl:155
	qs422016 := string(qb422016.B)
//line views/admin/comment_editnreview.qtpl:155
	qt422016.ReleaseByteBuffer(qb422016)
//line views/admin/comment_editnreview.qtpl:155
	return qs422016
//line views/admin/comment_editnreview.qtpl:155
}
