// Code generated by qtc from "page_admin_comment_editnreview.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// admin_comment_edit/review
//

//line model/page_admin_comment_editnreview.qtpl:3
package model

//line model/page_admin_comment_editnreview.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_admin_comment_editnreview.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_admin_comment_editnreview.qtpl:4
type AdminCommentEdit struct {
	BasePage
	DefaultTopic   Topic // 编辑/添加
	DefaultUser    User  // 默认作者
	DefaultComment CommentFmt
	GoBack         bool // 返回到编辑前页面
}

//line model/page_admin_comment_editnreview.qtpl:13
func (p *AdminCommentEdit) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_admin_comment_editnreview.qtpl:13
	qw422016.N().S(`

<div class="index">
    `)
//line model/page_admin_comment_editnreview.qtpl:16
	if p.PageName == "admin_comment_review" && len(p.DefaultComment.Content) == 0 {
//line model/page_admin_comment_editnreview.qtpl:16
		qw422016.N().S(`
        <h1>没有 `)
//line model/page_admin_comment_editnreview.qtpl:17
		qw422016.E().S(p.Title)
//line model/page_admin_comment_editnreview.qtpl:17
		qw422016.N().S(`</h1>
    `)
//line model/page_admin_comment_editnreview.qtpl:18
	} else {
//line model/page_admin_comment_editnreview.qtpl:18
		qw422016.N().S(`
    <h1>`)
//line model/page_admin_comment_editnreview.qtpl:19
		qw422016.E().S(p.Title)
//line model/page_admin_comment_editnreview.qtpl:19
		qw422016.N().S(`</h1>
    <p><a href="/t/`)
//line model/page_admin_comment_editnreview.qtpl:20
		qw422016.N().DUL(p.DefaultTopic.ID)
//line model/page_admin_comment_editnreview.qtpl:20
		qw422016.N().S(`" target="_blank">`)
//line model/page_admin_comment_editnreview.qtpl:20
		qw422016.E().S(p.DefaultTopic.Title)
//line model/page_admin_comment_editnreview.qtpl:20
		qw422016.N().S(`</a></p>
    <p>by `)
//line model/page_admin_comment_editnreview.qtpl:21
		qw422016.E().S(p.DefaultComment.Name)
//line model/page_admin_comment_editnreview.qtpl:21
		qw422016.N().S(` at `)
//line model/page_admin_comment_editnreview.qtpl:21
		qw422016.E().S(p.DefaultComment.AddTimeFmt)
//line model/page_admin_comment_editnreview.qtpl:21
		qw422016.N().S(`</p>
    <form class="pure-form" action="" method="post" onsubmit="form_post(); return false;">
        <div>
            <fieldset class="pure-group">
                <textarea id="id-content" class="pure-input-1 topic-con-input" placeholder="* 内容">`)
//line model/page_admin_comment_editnreview.qtpl:25
		qw422016.N().S(p.DefaultComment.Content)
//line model/page_admin_comment_editnreview.qtpl:25
		qw422016.N().S(`</textarea>
            </fieldset>
            <div id="id-msg"></div>
            <div class="fleft pure-button-group">
                <input id="btn-preview" type="button" value="预览" name="submit" onclick="previewComment(); return false;" class="pure-button button-success" />
                <input id="btn-submit" type="submit" value="发表" name="submit" onclick="submitComment(); return false;" class="pure-button pure-button-primary" />
                `)
//line model/page_admin_comment_editnreview.qtpl:31
		if p.PageName == "admin_comment_review" {
//line model/page_admin_comment_editnreview.qtpl:31
			qw422016.N().S(`
                <a href="?act=del" class="pure-button button-warning fr">直接删除</a>
                `)
//line model/page_admin_comment_editnreview.qtpl:33
		}
//line model/page_admin_comment_editnreview.qtpl:33
		qw422016.N().S(`
            </div>
            <div class="c"></div>

            <div id="id-preview" class="markdown-body entry-content"></div>
        </div>
    </form>

    <script>
        let btnReviewEle = document.getElementById("btn-preview");
        let conEle = document.getElementById("id-content");
        var msgEle = document.getElementById("id-msg");
        var reviewEle = document.getElementById("id-preview");

        function previewComment() {
            var con = conEle.value.trim();
            if (con === "") {
                conEle.focus();
                return
            }
            postAjax("/content/preview", JSON.stringify({Act: "commentPreview", Content: con}), function(data){
                var obj = JSON.parse(data)
                //console.log(obj);
                if(obj.Code === 200) {
                    msgEle.style.display = "none";
                    reviewEle.innerHTML = obj.Html;
                    reviewEle.style.display = "block";
                }else{
                    reviewEle.innerHTML = "";
                    reviewEle.style.display = "none";
                    msgEle.innerText = obj.Msg;
                }
            });
        }

        function submitComment() {
            var con = conEle.value.trim();
            if (con === "") {
                conEle.focus();
                return
            }
            postAjax("/admin/comment/edit", JSON.stringify({"ID": `)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().DUL(p.DefaultComment.ID)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().S(`, "TopicId": `)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().DUL(p.DefaultComment.TopicId)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().S(`, "ReplyId": `)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().DUL(p.DefaultComment.ReplyId)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().S(`, "Content": con, "UserId": `)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().DUL(p.DefaultComment.UserId)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().S(`, "AddTime": `)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().DL(p.DefaultComment.AddTime)
//line model/page_admin_comment_editnreview.qtpl:74
		qw422016.N().S(`}), function(data){
                var obj = JSON.parse(data)
                msgEle.innerText = obj.Msg;
                conEle.focus();
                conEle.value = "";
                toReplyId = 0;
                if(obj.Code === 200) {
                    `)
//line model/page_admin_comment_editnreview.qtpl:81
		if p.GoBack {
//line model/page_admin_comment_editnreview.qtpl:81
			qw422016.N().S(`
                    window.location.href = "/t/`)
//line model/page_admin_comment_editnreview.qtpl:82
			qw422016.N().DUL(p.DefaultComment.TopicId)
//line model/page_admin_comment_editnreview.qtpl:82
			qw422016.N().S(`#r`)
//line model/page_admin_comment_editnreview.qtpl:82
			qw422016.N().DUL(p.DefaultComment.ID)
//line model/page_admin_comment_editnreview.qtpl:82
			qw422016.N().S(`";
                    return false;
                    `)
//line model/page_admin_comment_editnreview.qtpl:84
		}
//line model/page_admin_comment_editnreview.qtpl:84
		qw422016.N().S(`
                    `)
//line model/page_admin_comment_editnreview.qtpl:85
		if p.PageName == "admin_comment_review" {
//line model/page_admin_comment_editnreview.qtpl:85
			qw422016.N().S(`
                    window.location.href = "/admin/comment/review";
                    `)
//line model/page_admin_comment_editnreview.qtpl:87
		} else {
//line model/page_admin_comment_editnreview.qtpl:87
			qw422016.N().S(`
                    if(data.Tid > 0){
                        window.location.href = "/t/"+data.Tid;
                    }else{
                        window.location.href = "/admin/my/comment";
                    }
                    `)
//line model/page_admin_comment_editnreview.qtpl:93
		}
//line model/page_admin_comment_editnreview.qtpl:93
		qw422016.N().S(`
                    return false;
                } else if (obj.Code === 201) {
                    window.location.href = "/member/`)
//line model/page_admin_comment_editnreview.qtpl:96
		qw422016.N().DUL(p.CurrentUser.ID)
//line model/page_admin_comment_editnreview.qtpl:96
		qw422016.N().S(`?type=comment";
                    return false;
                }
                reviewEle.style.display = "none";
                msgEle.style.display = "block";
            });
        }

        document.addEventListener('paste', function (evt) {
            var url = "/file/upload";
            var items = evt.clipboardData && evt.clipboardData.items;
            var file = null;
            if(items && items.length) {
                for(var i=0; i!==items.length; i++) {
                    if(items[i].type.indexOf('image') !== -1) {
                        file = items[i].getAsFile();
                        if(!!!file) {
                            continue;
                        }

                        // upload file object.
                        var form = new FormData();
                        form.append('file', file);

                        postAjax("/file/upload", form, function(data){
                            let obj = JSON.parse(data)
                            //console.log(obj);
                            if(obj.Code === 200) {
                                let img_url = "\n" + obj.Url + "\n";
                                let pos = conEle.selectionStart;
                                let con = conEle.value;
                                conEle.value = con.slice(0, pos) + img_url + con.slice(pos);
                            }else{
                                console.warn(obj.Msg);
                            }
                        });
                    }
                }
            }

        });
    </script>

    `)
//line model/page_admin_comment_editnreview.qtpl:139
	}
//line model/page_admin_comment_editnreview.qtpl:139
	qw422016.N().S(`

</div>

`)
//line model/page_admin_comment_editnreview.qtpl:143
}

//line model/page_admin_comment_editnreview.qtpl:143
func (p *AdminCommentEdit) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_admin_comment_editnreview.qtpl:143
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_admin_comment_editnreview.qtpl:143
	p.StreamMainBody(qw422016)
//line model/page_admin_comment_editnreview.qtpl:143
	qt422016.ReleaseWriter(qw422016)
//line model/page_admin_comment_editnreview.qtpl:143
}

//line model/page_admin_comment_editnreview.qtpl:143
func (p *AdminCommentEdit) MainBody() string {
//line model/page_admin_comment_editnreview.qtpl:143
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_admin_comment_editnreview.qtpl:143
	p.WriteMainBody(qb422016)
//line model/page_admin_comment_editnreview.qtpl:143
	qs422016 := string(qb422016.B)
//line model/page_admin_comment_editnreview.qtpl:143
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_admin_comment_editnreview.qtpl:143
	return qs422016
//line model/page_admin_comment_editnreview.qtpl:143
}
