// Code generated by qtc from "page_member.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// 首页文章列表，继承 TopicLstPage ，只修改 MainBody()
//

//line model/page_member.qtpl:3
package model

//line model/page_member.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_member.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_member.qtpl:4
type MemberPage struct {
	TopicLstPage
	UserFmt          UserFmt
	LstType          string
	TitleText        string
	CommentReviewLst []CommentReview // 待评论信息
	TopicLst         []TopicRecForm  // 待审核帖子列表
}

//line model/page_member.qtpl:14
func (p *MemberPage) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_member.qtpl:14
	qw422016.N().S(`

<div class="index">
    <div class="user-detail bot-line">
        <img src="/static/avatar/`)
//line model/page_member.qtpl:18
	qw422016.N().DUL(p.UserFmt.ID)
//line model/page_member.qtpl:18
	qw422016.N().S(`.jpg" alt="`)
//line model/page_member.qtpl:18
	qw422016.E().S(p.UserFmt.Name)
//line model/page_member.qtpl:18
	qw422016.N().S(` avatar" class="avatar right" >
        <h1>
        会员: `)
//line model/page_member.qtpl:20
	qw422016.E().S(p.UserFmt.Name)
//line model/page_member.qtpl:20
	qw422016.N().S(`
        `)
//line model/page_member.qtpl:21
	if p.CurrentUser.Flag >= 99 {
//line model/page_member.qtpl:21
		qw422016.N().S(`
        - <a href="/admin/user?id=`)
//line model/page_member.qtpl:22
		qw422016.N().DUL(p.UserFmt.ID)
//line model/page_member.qtpl:22
		qw422016.N().S(`">Edit</a>
        `)
//line model/page_member.qtpl:23
	}
//line model/page_member.qtpl:23
	qw422016.N().S(`
        </h1>
        <ul class="user-info">
            <li>注册时间： `)
//line model/page_member.qtpl:26
	qw422016.E().S(p.UserFmt.RegTimeFmt)
//line model/page_member.qtpl:26
	qw422016.N().S(`</li>
            <li>Web: <a href="`)
//line model/page_member.qtpl:27
	qw422016.E().S(p.UserFmt.Url)
//line model/page_member.qtpl:27
	qw422016.N().S(`" target="_blank">`)
//line model/page_member.qtpl:27
	qw422016.E().S(p.UserFmt.Url)
//line model/page_member.qtpl:27
	qw422016.N().S(`</a></li>
            <li>About: `)
//line model/page_member.qtpl:28
	qw422016.E().S(p.UserFmt.About)
//line model/page_member.qtpl:28
	qw422016.N().S(`</li>
        </ul>
        <div class="pure-button-group">
            <a class="pure-button `)
//line model/page_member.qtpl:31
	if p.LstType == "topic" {
//line model/page_member.qtpl:31
		qw422016.N().S(`pure-button-active`)
//line model/page_member.qtpl:31
	}
//line model/page_member.qtpl:31
	qw422016.N().S(`" href="?type=topic">主题</a>
            <a class="pure-button `)
//line model/page_member.qtpl:32
	if p.LstType == "comment" {
//line model/page_member.qtpl:32
		qw422016.N().S(`pure-button-active`)
//line model/page_member.qtpl:32
	}
//line model/page_member.qtpl:32
	qw422016.N().S(`" href="?type=comment">评论</a>
        </div>
    </div>

    `)
//line model/page_member.qtpl:36
	if len(p.TopicLst) > 0 {
//line model/page_member.qtpl:36
		qw422016.N().S(`
    <h2 class="bot-line">待审核主题</h2>
    <ul class="bot-line">
        `)
//line model/page_member.qtpl:39
		for _, item := range p.TopicLst {
//line model/page_member.qtpl:39
			qw422016.N().S(`
        <li>
            [`)
//line model/page_member.qtpl:41
			qw422016.E().S(item.AddTimeFmt)
//line model/page_member.qtpl:41
			qw422016.N().S(`] `)
//line model/page_member.qtpl:41
			qw422016.E().S(item.Title)
//line model/page_member.qtpl:41
			qw422016.N().S(` <br>&nbsp;
        </li>
        `)
//line model/page_member.qtpl:43
		}
//line model/page_member.qtpl:43
		qw422016.N().S(`
    </ul>
    `)
//line model/page_member.qtpl:45
	}
//line model/page_member.qtpl:45
	qw422016.N().S(`

    `)
//line model/page_member.qtpl:47
	if len(p.CommentReviewLst) > 0 {
//line model/page_member.qtpl:47
		qw422016.N().S(`
    <h2 class="bot-line">待审核评论</h2>
    <ul class="bot-line">
        `)
//line model/page_member.qtpl:50
		for _, item := range p.CommentReviewLst {
//line model/page_member.qtpl:50
			qw422016.N().S(`
        <li>
            主题: <a href="/t/`)
//line model/page_member.qtpl:52
			qw422016.N().DUL(item.TopicId)
//line model/page_member.qtpl:52
			qw422016.N().S(`">`)
//line model/page_member.qtpl:52
			qw422016.E().S(item.TopicTitle)
//line model/page_member.qtpl:52
			qw422016.N().S(`</a><br>
            <div class="gray">`)
//line model/page_member.qtpl:53
			qw422016.E().S(item.AddTimeFmt)
//line model/page_member.qtpl:53
			qw422016.N().S(`</div>
            <div class="markdown-body entry-content">
                `)
//line model/page_member.qtpl:55
			qw422016.N().S(item.ContentFmt)
//line model/page_member.qtpl:55
			qw422016.N().S(`
            </div>
        </li>
        `)
//line model/page_member.qtpl:58
		}
//line model/page_member.qtpl:58
		qw422016.N().S(`
    </ul>
    `)
//line model/page_member.qtpl:60
	}
//line model/page_member.qtpl:60
	qw422016.N().S(`

    `)
//line model/page_member.qtpl:62
	for _, item := range p.TopicPageInfo.Items {
//line model/page_member.qtpl:62
		qw422016.N().S(`
    <article>

        <header>
            `)
//line model/page_member.qtpl:66
		if item.Comments > 0 {
//line model/page_member.qtpl:66
			qw422016.N().S(`
            <a href="/t/`)
//line model/page_member.qtpl:67
			qw422016.N().DUL(item.ID)
//line model/page_member.qtpl:67
			qw422016.N().S(`#r`)
//line model/page_member.qtpl:67
			qw422016.N().DUL(item.Comments)
//line model/page_member.qtpl:67
			qw422016.N().S(`"><img alt="`)
//line model/page_member.qtpl:67
			qw422016.E().S(item.Title)
//line model/page_member.qtpl:67
			qw422016.N().S(` icon" src="/icon/t/`)
//line model/page_member.qtpl:67
			qw422016.N().DUL(item.ID)
//line model/page_member.qtpl:67
			qw422016.N().S(`.jpg?r=`)
//line model/page_member.qtpl:67
			qw422016.N().DUL(item.Comments)
//line model/page_member.qtpl:67
			qw422016.N().S(`" class="avatar"></a>
            `)
//line model/page_member.qtpl:68
		} else {
//line model/page_member.qtpl:68
			qw422016.N().S(`
            <a href="/t/`)
//line model/page_member.qtpl:69
			qw422016.N().DUL(item.ID)
//line model/page_member.qtpl:69
			qw422016.N().S(`"><img alt="`)
//line model/page_member.qtpl:69
			qw422016.E().S(item.Title)
//line model/page_member.qtpl:69
			qw422016.N().S(` icon" src="/static/avatar/`)
//line model/page_member.qtpl:69
			qw422016.N().DUL(item.UserId)
//line model/page_member.qtpl:69
			qw422016.N().S(`.jpg" class="avatar"></a>
            `)
//line model/page_member.qtpl:70
		}
//line model/page_member.qtpl:70
		qw422016.N().S(`
            <h1><a href="/t/`)
//line model/page_member.qtpl:71
		qw422016.N().DUL(item.ID)
//line model/page_member.qtpl:71
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line model/page_member.qtpl:71
		qw422016.E().S(item.Title)
//line model/page_member.qtpl:71
		qw422016.N().S(`">`)
//line model/page_member.qtpl:71
		qw422016.E().S(item.Title)
//line model/page_member.qtpl:71
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line model/page_member.qtpl:73
		qw422016.N().DUL(item.NodeId)
//line model/page_member.qtpl:73
		qw422016.N().S(`">`)
//line model/page_member.qtpl:73
		qw422016.E().S(item.NodeName)
//line model/page_member.qtpl:73
		qw422016.N().S(`</a>
                <a href="/member/`)
//line model/page_member.qtpl:74
		qw422016.N().DUL(item.UserId)
//line model/page_member.qtpl:74
		qw422016.N().S(`" rel="nofollow">`)
//line model/page_member.qtpl:74
		qw422016.E().S(item.AuthorName)
//line model/page_member.qtpl:74
		qw422016.N().S(`</a>
                <time datetime="`)
//line model/page_member.qtpl:75
		qw422016.E().S(item.AddTimeFmt)
//line model/page_member.qtpl:75
		qw422016.N().S(`" pubdate data-updated="true">`)
//line model/page_member.qtpl:75
		qw422016.E().S(item.EditTimeFmt)
//line model/page_member.qtpl:75
		qw422016.N().S(`</time>
                `)
//line model/page_member.qtpl:76
		if item.Comments > 0 {
//line model/page_member.qtpl:76
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line model/page_member.qtpl:77
			qw422016.N().DUL(item.ID)
//line model/page_member.qtpl:77
			qw422016.N().S(`#r`)
//line model/page_member.qtpl:77
			qw422016.N().DUL(item.Comments)
//line model/page_member.qtpl:77
			qw422016.N().S(`" title="Comment on `)
//line model/page_member.qtpl:77
			qw422016.E().S(item.Title)
//line model/page_member.qtpl:77
			qw422016.N().S(`" rel="nofollow">`)
//line model/page_member.qtpl:77
			qw422016.N().DUL(item.Comments)
//line model/page_member.qtpl:77
			qw422016.N().S(`</a>
                `)
//line model/page_member.qtpl:78
		}
//line model/page_member.qtpl:78
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line model/page_member.qtpl:84
	}
//line model/page_member.qtpl:84
	qw422016.N().S(`

    <div class="pagination">
        `)
//line model/page_member.qtpl:87
	if p.TopicPageInfo.HasPrev {
//line model/page_member.qtpl:87
		qw422016.N().S(`
        <a class="prev" href="?type=`)
//line model/page_member.qtpl:88
		qw422016.E().S(p.LstType)
//line model/page_member.qtpl:88
		qw422016.N().S(`&btn=prev&key=`)
//line model/page_member.qtpl:88
		qw422016.N().DUL(p.TopicPageInfo.FirstKey)
//line model/page_member.qtpl:88
		qw422016.N().S(`&score=`)
//line model/page_member.qtpl:88
		qw422016.N().DUL(p.TopicPageInfo.FirstScore)
//line model/page_member.qtpl:88
		qw422016.N().S(`">← Newer</a>
        `)
//line model/page_member.qtpl:89
	}
//line model/page_member.qtpl:89
	qw422016.N().S(`
        `)
//line model/page_member.qtpl:90
	if p.TopicPageInfo.HasNext {
//line model/page_member.qtpl:90
		qw422016.N().S(`
        <a class="next" href="?type=`)
//line model/page_member.qtpl:91
		qw422016.E().S(p.LstType)
//line model/page_member.qtpl:91
		qw422016.N().S(`&btn=next&key=`)
//line model/page_member.qtpl:91
		qw422016.N().DUL(p.TopicPageInfo.LastKey)
//line model/page_member.qtpl:91
		qw422016.N().S(`&score=`)
//line model/page_member.qtpl:91
		qw422016.N().DUL(p.TopicPageInfo.LastScore)
//line model/page_member.qtpl:91
		qw422016.N().S(`">Older →</a>
        `)
//line model/page_member.qtpl:92
	}
//line model/page_member.qtpl:92
	qw422016.N().S(`
    </div>

</div>

`)
//line model/page_member.qtpl:97
}

//line model/page_member.qtpl:97
func (p *MemberPage) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_member.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_member.qtpl:97
	p.StreamMainBody(qw422016)
//line model/page_member.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line model/page_member.qtpl:97
}

//line model/page_member.qtpl:97
func (p *MemberPage) MainBody() string {
//line model/page_member.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_member.qtpl:97
	p.WriteMainBody(qb422016)
//line model/page_member.qtpl:97
	qs422016 := string(qb422016.B)
//line model/page_member.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_member.qtpl:97
	return qs422016
//line model/page_member.qtpl:97
}
