// Code generated by qtc from "page_home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// 首页文章列表，继承 TopicLstPage ，只修改 MainBody()
//

//line model/page_home.qtpl:3
package model

//line model/page_home.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_home.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_home.qtpl:4
type HomePage struct {
	TopicLstPage
}

//line model/page_home.qtpl:9
func (p *HomePage) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_home.qtpl:9
	qw422016.N().S(`

<div class="index">

    `)
//line model/page_home.qtpl:13
	for _, item := range p.TopicPageInfo.Items {
//line model/page_home.qtpl:13
		qw422016.N().S(`
    <article>

        <header>
            `)
//line model/page_home.qtpl:17
		if item.Comments > 0 {
//line model/page_home.qtpl:17
			qw422016.N().S(`
            <a href="/t/`)
//line model/page_home.qtpl:18
			qw422016.N().DUL(item.ID)
//line model/page_home.qtpl:18
			qw422016.N().S(`#r`)
//line model/page_home.qtpl:18
			qw422016.N().DUL(item.Comments)
//line model/page_home.qtpl:18
			qw422016.N().S(`"><img alt="`)
//line model/page_home.qtpl:18
			qw422016.E().S(item.Title)
//line model/page_home.qtpl:18
			qw422016.N().S(` icon" src="/icon/t/`)
//line model/page_home.qtpl:18
			qw422016.N().DUL(item.ID)
//line model/page_home.qtpl:18
			qw422016.N().S(`.jpg?r=`)
//line model/page_home.qtpl:18
			qw422016.N().DUL(item.Comments)
//line model/page_home.qtpl:18
			qw422016.N().S(`" class="avatar"></a>
            `)
//line model/page_home.qtpl:19
		} else {
//line model/page_home.qtpl:19
			qw422016.N().S(`
            <a href="/t/`)
//line model/page_home.qtpl:20
			qw422016.N().DUL(item.ID)
//line model/page_home.qtpl:20
			qw422016.N().S(`"><img alt="`)
//line model/page_home.qtpl:20
			qw422016.E().S(item.Title)
//line model/page_home.qtpl:20
			qw422016.N().S(` icon" src="/static/avatar/`)
//line model/page_home.qtpl:20
			qw422016.N().DUL(item.UserId)
//line model/page_home.qtpl:20
			qw422016.N().S(`.jpg" class="avatar"></a>
            `)
//line model/page_home.qtpl:21
		}
//line model/page_home.qtpl:21
		qw422016.N().S(`
            <h1><a href="/t/`)
//line model/page_home.qtpl:22
		qw422016.N().DUL(item.ID)
//line model/page_home.qtpl:22
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line model/page_home.qtpl:22
		qw422016.E().S(item.Title)
//line model/page_home.qtpl:22
		qw422016.N().S(`">`)
//line model/page_home.qtpl:22
		qw422016.E().S(item.Title)
//line model/page_home.qtpl:22
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line model/page_home.qtpl:24
		qw422016.N().DUL(item.NodeId)
//line model/page_home.qtpl:24
		qw422016.N().S(`">`)
//line model/page_home.qtpl:24
		qw422016.E().S(item.NodeName)
//line model/page_home.qtpl:24
		qw422016.N().S(`</a>
                <a href="/member/`)
//line model/page_home.qtpl:25
		qw422016.N().DUL(item.UserId)
//line model/page_home.qtpl:25
		qw422016.N().S(`" rel="nofollow">`)
//line model/page_home.qtpl:25
		qw422016.E().S(item.AuthorName)
//line model/page_home.qtpl:25
		qw422016.N().S(`</a>
                <time datetime="`)
//line model/page_home.qtpl:26
		qw422016.E().S(item.AddTimeFmt)
//line model/page_home.qtpl:26
		qw422016.N().S(`" pubdate data-updated="true">`)
//line model/page_home.qtpl:26
		qw422016.E().S(item.EditTimeFmt)
//line model/page_home.qtpl:26
		qw422016.N().S(`</time>
                `)
//line model/page_home.qtpl:27
		if item.Comments > 0 {
//line model/page_home.qtpl:27
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line model/page_home.qtpl:28
			qw422016.N().DUL(item.ID)
//line model/page_home.qtpl:28
			qw422016.N().S(`#r`)
//line model/page_home.qtpl:28
			qw422016.N().DUL(item.Comments)
//line model/page_home.qtpl:28
			qw422016.N().S(`" title="Comment on `)
//line model/page_home.qtpl:28
			qw422016.E().S(item.Title)
//line model/page_home.qtpl:28
			qw422016.N().S(`" rel="nofollow">`)
//line model/page_home.qtpl:28
			qw422016.N().DUL(item.Comments)
//line model/page_home.qtpl:28
			qw422016.N().S(`</a>
                `)
//line model/page_home.qtpl:29
		}
//line model/page_home.qtpl:29
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line model/page_home.qtpl:35
	}
//line model/page_home.qtpl:35
	qw422016.N().S(`

    <div class="pagination">
        `)
//line model/page_home.qtpl:38
	if p.TopicPageInfo.HasPrev {
//line model/page_home.qtpl:38
		qw422016.N().S(`
        <a class="prev" href="/?btn=prev&key=`)
//line model/page_home.qtpl:39
		qw422016.N().DUL(p.TopicPageInfo.FirstKey)
//line model/page_home.qtpl:39
		qw422016.N().S(`&score=`)
//line model/page_home.qtpl:39
		qw422016.N().DUL(p.TopicPageInfo.FirstScore)
//line model/page_home.qtpl:39
		qw422016.N().S(`">← Newer</a>
        `)
//line model/page_home.qtpl:40
	}
//line model/page_home.qtpl:40
	qw422016.N().S(`
        `)
//line model/page_home.qtpl:41
	if p.TopicPageInfo.HasNext {
//line model/page_home.qtpl:41
		qw422016.N().S(`
        <a class="next" href="/?btn=next&key=`)
//line model/page_home.qtpl:42
		qw422016.N().DUL(p.TopicPageInfo.LastKey)
//line model/page_home.qtpl:42
		qw422016.N().S(`&score=`)
//line model/page_home.qtpl:42
		qw422016.N().DUL(p.TopicPageInfo.LastScore)
//line model/page_home.qtpl:42
		qw422016.N().S(`">Older →</a>
        `)
//line model/page_home.qtpl:43
	}
//line model/page_home.qtpl:43
	qw422016.N().S(`
    </div>

</div>

`)
//line model/page_home.qtpl:48
}

//line model/page_home.qtpl:48
func (p *HomePage) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_home.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_home.qtpl:48
	p.StreamMainBody(qw422016)
//line model/page_home.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line model/page_home.qtpl:48
}

//line model/page_home.qtpl:48
func (p *HomePage) MainBody() string {
//line model/page_home.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_home.qtpl:48
	p.WriteMainBody(qb422016)
//line model/page_home.qtpl:48
	qs422016 := string(qb422016.B)
//line model/page_home.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_home.qtpl:48
	return qs422016
//line model/page_home.qtpl:48
}
