// Code generated by qtc from "page_user_loginnregister.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// admin_login
//

//line model/page_user_loginnregister.qtpl:3
package model

//line model/page_user_loginnregister.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_user_loginnregister.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_user_loginnregister.qtpl:4
type UserLogin struct {
	BasePage
	Act          string
	Token        string
	CaptchaId    string
	HasOtherAuth bool
	DefaultName  string
}

//line model/page_user_loginnregister.qtpl:14
func (p *UserLogin) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_user_loginnregister.qtpl:14
	qw422016.N().S(`
<script src="/static/js/md5.min.js" type="text/javascript"></script>
<div class="index">
    <header class="bot-line">
        <h1 class="entry-title">`)
//line model/page_user_loginnregister.qtpl:18
	qw422016.E().S(p.Title)
//line model/page_user_loginnregister.qtpl:18
	qw422016.N().S(`</h1>
    </header>
    <h2>账号密码 - `)
//line model/page_user_loginnregister.qtpl:20
	qw422016.E().S(p.Title)
//line model/page_user_loginnregister.qtpl:20
	qw422016.N().S(`</h2>
    <form class="pure-form pure-form-aligned" action="" method="post" onsubmit="form_post(); return false;">
        <fieldset>
            <div class="pure-control-group">
                <label for="name">登录名： </label>
                <input id="name" type="text" value="`)
//line model/page_user_loginnregister.qtpl:25
	qw422016.E().S(p.DefaultName)
//line model/page_user_loginnregister.qtpl:25
	qw422016.N().S(`" autofocus>
            </div>

            <div class="pure-control-group">
                <label for="password">密　码： </label>
                <input id="password" type="password">
            </div>

            `)
//line model/page_user_loginnregister.qtpl:33
	if p.Act == "register" {
//line model/page_user_loginnregister.qtpl:33
		qw422016.N().S(`
            <div class="pure-control-group">
                <label for="password">重　复： </label>
                <input id="password2" type="password">
            </div>
            `)
//line model/page_user_loginnregister.qtpl:38
	} else {
//line model/page_user_loginnregister.qtpl:38
		qw422016.N().S(`
            <input id="password2" type="hidden" value="">
            `)
//line model/page_user_loginnregister.qtpl:40
	}
//line model/page_user_loginnregister.qtpl:40
	qw422016.N().S(`

            <div class="pure-control-group">
                <label for="image"></label>
                <span class="pure-form-message-inline"><img id="image" onclick="reload()" src="/captcha/`)
//line model/page_user_loginnregister.qtpl:44
	qw422016.E().S(p.CaptchaId)
//line model/page_user_loginnregister.qtpl:44
	qw422016.N().S(`.png" alt="Captcha image"></span>
            </div>

            <div class="pure-control-group">
                <label for="captchaSolution">验证码： </label>
                <input id="captchaSolution" type="number">
            </div>

            <div class="pure-controls">
                <span id="id-msg"></span>
                <button type="submit" id="submit" class="pure-button pure-button-primary"> `)
//line model/page_user_loginnregister.qtpl:54
	qw422016.E().S(p.Title)
//line model/page_user_loginnregister.qtpl:54
	qw422016.N().S(` </button>
            </div>
        </fieldset>
    </form>

    `)
//line model/page_user_loginnregister.qtpl:59
	if p.HasOtherAuth {
//line model/page_user_loginnregister.qtpl:59
		qw422016.N().S(`
    <h2>其它登录方式</h2>
    `)
//line model/page_user_loginnregister.qtpl:61
		if p.SiteCf.QQClientID != "" {
//line model/page_user_loginnregister.qtpl:61
			qw422016.N().S(`
    <a href="/qqlogin" rel="nofollow"><img src="/static/images/icon_qq_64.png" alt="QQ登录" class="avatar"></a>
    `)
//line model/page_user_loginnregister.qtpl:63
		}
//line model/page_user_loginnregister.qtpl:63
		qw422016.N().S(`
    `)
//line model/page_user_loginnregister.qtpl:64
		if p.SiteCf.WeiboClientID != "" {
//line model/page_user_loginnregister.qtpl:64
			qw422016.N().S(`
    <a href="/wblogin" rel="nofollow"><img src="/static/images/icon_weibo_64.png" alt="微博登录" class="avatar"></a>
    `)
//line model/page_user_loginnregister.qtpl:66
		}
//line model/page_user_loginnregister.qtpl:66
		qw422016.N().S(`
    `)
//line model/page_user_loginnregister.qtpl:67
		if p.SiteCf.GithubClientID != "" {
//line model/page_user_loginnregister.qtpl:67
			qw422016.N().S(`
    <a href="/githublogin" rel="nofollow"><img src="/static/images/icon_github_64.png" alt="github登录" class="avatar"></a>
    `)
//line model/page_user_loginnregister.qtpl:69
		}
//line model/page_user_loginnregister.qtpl:69
		qw422016.N().S(`
    `)
//line model/page_user_loginnregister.qtpl:70
	}
//line model/page_user_loginnregister.qtpl:70
	qw422016.N().S(`

    <script>
        var captchaId = '`)
//line model/page_user_loginnregister.qtpl:73
	qw422016.E().S(p.CaptchaId)
//line model/page_user_loginnregister.qtpl:73
	qw422016.N().S(`';
        function setSrcQuery(e, q) {
            var src  = e.src;
            var p = src.indexOf('?');
            if (p >= 0) {
                src = src.substr(0, p);
            }
            e.src = src + "?" + q
        }

        function reload() {
            setSrcQuery(document.getElementById('image'), "reload=" + (new Date()).getTime());
            document.getElementById('captchaSolution').value = "";
            return false;
        }

        function form_post(){
            let msgEle = document.getElementById("id-msg");
            let name = document.getElementById('name').value.trim();
            let password = document.getElementById('password').value.trim();
            let password2 = document.getElementById('password2').value.trim();

            if(password2) {
                if(password !== password2) {
                    msgEle.style.display = "block";
                    msgEle.style.color = "red";
                    msgEle.innerText = "两次输入密码不一样";
                    return false;
                }
            }

            let captchaSolution = document.getElementById('captchaSolution').value.trim();
            if(name && password && captchaSolution){
                msgEle.style.display = "none";
                postAjax("/`)
//line model/page_user_loginnregister.qtpl:107
	qw422016.E().S(p.Act)
//line model/page_user_loginnregister.qtpl:107
	qw422016.N().S(`", JSON.stringify({'Act': '`)
//line model/page_user_loginnregister.qtpl:107
	qw422016.E().S(p.Act)
//line model/page_user_loginnregister.qtpl:107
	qw422016.N().S(`', 'Name': name, 'Password': md5(password), 'CaptchaSolution': captchaSolution, 'CaptchaId': captchaId}), function(data){
                    let obj = JSON.parse(data)
                    //console.log(obj);
                    if(obj.Code === 200) {
                        window.location.href = "/";
                        return false;
                    } else {
                        msgEle.style.display = "block";
                        msgEle.style.color = "red";
                        msgEle.innerText = obj.Msg;
                        if (obj.Code === 405) {
                            document.getElementById('image').src = "/captcha/"+obj.NewCaptchaId+".png";
                            captchaId = obj.NewCaptchaId;
                            document.getElementById('captchaSolution').value = "";
                            return false;
                        }else{
                            reload();
                        }
                    }
                });
            }
            return false;
        }

    </script>

</div>

`)
//line model/page_user_loginnregister.qtpl:135
}

//line model/page_user_loginnregister.qtpl:135
func (p *UserLogin) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_user_loginnregister.qtpl:135
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_user_loginnregister.qtpl:135
	p.StreamMainBody(qw422016)
//line model/page_user_loginnregister.qtpl:135
	qt422016.ReleaseWriter(qw422016)
//line model/page_user_loginnregister.qtpl:135
}

//line model/page_user_loginnregister.qtpl:135
func (p *UserLogin) MainBody() string {
//line model/page_user_loginnregister.qtpl:135
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_user_loginnregister.qtpl:135
	p.WriteMainBody(qb422016)
//line model/page_user_loginnregister.qtpl:135
	qs422016 := string(qb422016.B)
//line model/page_user_loginnregister.qtpl:135
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_user_loginnregister.qtpl:135
	return qs422016
//line model/page_user_loginnregister.qtpl:135
}
