// Code generated by qtc from "page_admin_link.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// admin_login
//

//line model/page_admin_link.qtpl:3
package model

//line model/page_admin_link.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_admin_link.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_admin_link.qtpl:4
type AdminLink struct {
	BasePage
	Act  string // 行为名称，添加/编辑
	Link Link
}

//line model/page_admin_link.qtpl:11
func (p *AdminLink) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_admin_link.qtpl:11
	qw422016.N().S(`
<div class="index">
    <div class="markdown-body entry-content">
    <h1>`)
//line model/page_admin_link.qtpl:14
	qw422016.E().S(p.Title)
//line model/page_admin_link.qtpl:14
	qw422016.N().S(`</h1>

    <form action="" method="post" class="pure-form pure-form-stacked">
        <fieldset>
            <legend>`)
//line model/page_admin_link.qtpl:18
	qw422016.E().S(p.Act)
//line model/page_admin_link.qtpl:18
	qw422016.N().S(` 链接</legend>

            <p>Score: 显示排序，大排前</p>

            <div class="pure-g">
                <div class="pure-u-1 pure-u-sm-1-5">
                    <label for="Name">Name</label>
                    <input id="Name" name="Name" class="pure-u-23-24" type="text" value="`)
//line model/page_admin_link.qtpl:25
	qw422016.E().S(p.Link.Name)
//line model/page_admin_link.qtpl:25
	qw422016.N().S(`" required>
                </div>

                <div class="pure-u-1 pure-u-sm-1-5">
                    <label for="Score">Score</label>
                    <input id="Score" name="Score" class="pure-u-23-24" type="number" value="`)
//line model/page_admin_link.qtpl:30
	qw422016.N().D(p.Link.Score)
//line model/page_admin_link.qtpl:30
	qw422016.N().S(`" required>
                </div>

                <div class="pure-u-1 pure-u-sm-2-5">
                    <label for="Url">Url</label>
                    <input id="Url" name="Url" class="pure-u-23-24" type="text" value="`)
//line model/page_admin_link.qtpl:35
	qw422016.E().S(p.Link.Url)
//line model/page_admin_link.qtpl:35
	qw422016.N().S(`" required>
                </div>

            </div>

            <button type="submit" class="pure-button pure-button-primary">提交</button>
        </fieldset>
    </form>

    <h2>链接列表</h2>

    <ul>
        <li class="bot-line">
            ID - Name - Score - Url
        </li>
        `)
//line model/page_admin_link.qtpl:50
	for _, v := range p.LinkLst {
//line model/page_admin_link.qtpl:50
		qw422016.N().S(`
        <li class="bot-line">
            `)
//line model/page_admin_link.qtpl:52
		qw422016.N().DUL(v.ID)
//line model/page_admin_link.qtpl:52
		qw422016.N().S(` - <a href="/admin/link?id=`)
//line model/page_admin_link.qtpl:52
		qw422016.N().DUL(v.ID)
//line model/page_admin_link.qtpl:52
		qw422016.N().S(`">`)
//line model/page_admin_link.qtpl:52
		qw422016.E().S(v.Name)
//line model/page_admin_link.qtpl:52
		qw422016.N().S(`</a> - `)
//line model/page_admin_link.qtpl:52
		qw422016.N().D(v.Score)
//line model/page_admin_link.qtpl:52
		qw422016.N().S(` - `)
//line model/page_admin_link.qtpl:52
		qw422016.E().S(v.Url)
//line model/page_admin_link.qtpl:52
		qw422016.N().S(`
        </li>
        `)
//line model/page_admin_link.qtpl:54
	}
//line model/page_admin_link.qtpl:54
	qw422016.N().S(`
    </ul>

    </div>
</div>

`)
//line model/page_admin_link.qtpl:60
}

//line model/page_admin_link.qtpl:60
func (p *AdminLink) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_admin_link.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_admin_link.qtpl:60
	p.StreamMainBody(qw422016)
//line model/page_admin_link.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line model/page_admin_link.qtpl:60
}

//line model/page_admin_link.qtpl:60
func (p *AdminLink) MainBody() string {
//line model/page_admin_link.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_admin_link.qtpl:60
	p.WriteMainBody(qb422016)
//line model/page_admin_link.qtpl:60
	qs422016 := string(qb422016.B)
//line model/page_admin_link.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_admin_link.qtpl:60
	return qs422016
//line model/page_admin_link.qtpl:60
}
