// Code generated by qtc from "page_my_msg.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// admin_login
//

//line model/page_my_msg.qtpl:3
package model

//line model/page_my_msg.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line model/page_my_msg.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line model/page_my_msg.qtpl:4
type MyMsg struct {
	BasePage
	TopicPageInfo TopicPageInfoMsg
}

//line model/page_my_msg.qtpl:10
func (p *MyMsg) StreamMainBody(qw422016 *qt422016.Writer) {
//line model/page_my_msg.qtpl:10
	qw422016.N().S(`
<div class="index">

    <h1>`)
//line model/page_my_msg.qtpl:13
	qw422016.E().S(p.Title)
//line model/page_my_msg.qtpl:13
	qw422016.N().S(`</h1>
    <p class="bot-line">有人在下面帖子回复里 @ 了你，请及时前往查看</p>

    `)
//line model/page_my_msg.qtpl:16
	for _, item := range p.TopicPageInfo.Items {
//line model/page_my_msg.qtpl:16
		qw422016.N().S(`
    <article>

        <header>
            <a href="/member/`)
//line model/page_my_msg.qtpl:20
		qw422016.N().DUL(item.UserId)
//line model/page_my_msg.qtpl:20
		qw422016.N().S(`" rel="nofollow"><img alt="`)
//line model/page_my_msg.qtpl:20
		qw422016.E().S(item.AuthorName)
//line model/page_my_msg.qtpl:20
		qw422016.N().S(` avatar" src="/static/avatar/`)
//line model/page_my_msg.qtpl:20
		qw422016.N().DUL(item.UserId)
//line model/page_my_msg.qtpl:20
		qw422016.N().S(`.jpg" class="avatar"></a>
            <h1><a href="/t/`)
//line model/page_my_msg.qtpl:21
		qw422016.N().DUL(item.ID)
//line model/page_my_msg.qtpl:21
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line model/page_my_msg.qtpl:21
		qw422016.E().S(item.Title)
//line model/page_my_msg.qtpl:21
		qw422016.N().S(`">`)
//line model/page_my_msg.qtpl:21
		qw422016.E().S(item.Title)
//line model/page_my_msg.qtpl:21
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line model/page_my_msg.qtpl:23
		qw422016.N().DUL(item.NodeId)
//line model/page_my_msg.qtpl:23
		qw422016.N().S(`">`)
//line model/page_my_msg.qtpl:23
		qw422016.E().S(item.NodeName)
//line model/page_my_msg.qtpl:23
		qw422016.N().S(`</a>
                <a href="/member/`)
//line model/page_my_msg.qtpl:24
		qw422016.N().DUL(item.UserId)
//line model/page_my_msg.qtpl:24
		qw422016.N().S(`" rel="nofollow">`)
//line model/page_my_msg.qtpl:24
		qw422016.E().S(item.AuthorName)
//line model/page_my_msg.qtpl:24
		qw422016.N().S(`</a>
                <time datetime="`)
//line model/page_my_msg.qtpl:25
		qw422016.E().S(item.AddTimeFmt)
//line model/page_my_msg.qtpl:25
		qw422016.N().S(`" pubdate data-updated="true">`)
//line model/page_my_msg.qtpl:25
		qw422016.E().S(item.EditTimeFmt)
//line model/page_my_msg.qtpl:25
		qw422016.N().S(`</time>
                `)
//line model/page_my_msg.qtpl:26
		if item.Comments > 0 {
//line model/page_my_msg.qtpl:26
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line model/page_my_msg.qtpl:27
			qw422016.N().DUL(item.ID)
//line model/page_my_msg.qtpl:27
			qw422016.N().S(`#r`)
//line model/page_my_msg.qtpl:27
			qw422016.N().DUL(item.Comments)
//line model/page_my_msg.qtpl:27
			qw422016.N().S(`" title="Comment on `)
//line model/page_my_msg.qtpl:27
			qw422016.E().S(item.Title)
//line model/page_my_msg.qtpl:27
			qw422016.N().S(`" rel="nofollow">`)
//line model/page_my_msg.qtpl:27
			qw422016.N().DUL(item.Comments)
//line model/page_my_msg.qtpl:27
			qw422016.N().S(`</a>
                `)
//line model/page_my_msg.qtpl:28
		}
//line model/page_my_msg.qtpl:28
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line model/page_my_msg.qtpl:34
	}
//line model/page_my_msg.qtpl:34
	qw422016.N().S(`

    <div class="top-line">
    `)
//line model/page_my_msg.qtpl:37
	if len(p.TopicPageInfo.Items) == 10 {
//line model/page_my_msg.qtpl:37
		qw422016.N().S(`
    * 以上只显示最早 10 条信息
    `)
//line model/page_my_msg.qtpl:39
	} else {
//line model/page_my_msg.qtpl:39
		qw422016.N().S(`
    &nbsp;
    `)
//line model/page_my_msg.qtpl:41
	}
//line model/page_my_msg.qtpl:41
	qw422016.N().S(`
    </div>

</div>

`)
//line model/page_my_msg.qtpl:46
}

//line model/page_my_msg.qtpl:46
func (p *MyMsg) WriteMainBody(qq422016 qtio422016.Writer) {
//line model/page_my_msg.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line model/page_my_msg.qtpl:46
	p.StreamMainBody(qw422016)
//line model/page_my_msg.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line model/page_my_msg.qtpl:46
}

//line model/page_my_msg.qtpl:46
func (p *MyMsg) MainBody() string {
//line model/page_my_msg.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line model/page_my_msg.qtpl:46
	p.WriteMainBody(qb422016)
//line model/page_my_msg.qtpl:46
	qs422016 := string(qb422016.B)
//line model/page_my_msg.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line model/page_my_msg.qtpl:46
	return qs422016
//line model/page_my_msg.qtpl:46
}
