// Code generated by qtc from "admin_node.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ybs/admin_node.qtpl:1
package ybs

//line views/ybs/admin_node.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/admin_node.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/admin_node.qtpl:1
func (p *AdminNode) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/admin_node.qtpl:1
	qw422016.N().S(`
<div class="index">
    <div class="markdown-body entry-content">
    <h1>`)
//line views/ybs/admin_node.qtpl:4
	qw422016.E().S(p.Title)
//line views/ybs/admin_node.qtpl:4
	qw422016.N().S(`</h1>

    <form action="" method="post" class="pure-form pure-form-stacked">
        <fieldset>
            <legend>`)
//line views/ybs/admin_node.qtpl:8
	qw422016.E().S(p.Act)
//line views/ybs/admin_node.qtpl:8
	qw422016.N().S(` 节点</legend>

            <p>Score: 显示排序，大排前</p>

            <div class="pure-g">
                <div class="pure-u-1 pure-u-sm-1-6">
                    <label for="Name">Name</label>
                    <input id="Name" name="Name" class="pure-u-23-24" type="text" value="`)
//line views/ybs/admin_node.qtpl:15
	qw422016.E().S(p.Node.Name)
//line views/ybs/admin_node.qtpl:15
	qw422016.N().S(`" required>
                </div>

                <div class="pure-u-1 pure-u-sm-1-6">
                    <label for="Score">Score</label>
                    <input id="Score" name="Score" class="pure-u-23-24" type="number" value="`)
//line views/ybs/admin_node.qtpl:20
	qw422016.N().D(p.Node.Score)
//line views/ybs/admin_node.qtpl:20
	qw422016.N().S(`" required>
                </div>

            </div>

            <div class="pure-g">
                <div class="pure-u-1 pure-u-sm-1-1">
                    <label for="About">About</label>
                    <textarea id="About" name="About" class="pure-input-1">`)
//line views/ybs/admin_node.qtpl:28
	qw422016.E().S(p.Node.About)
//line views/ybs/admin_node.qtpl:28
	qw422016.N().S(`</textarea>
                </div>
            </div>


            <button type="submit" class="pure-button pure-button-primary">提交</button>
        </fieldset>
    </form>

    <h2>节点列表</h2>
    <ul>
        <li class="bot-line">
            ID - Name - Score - About
        </li>
        `)
//line views/ybs/admin_node.qtpl:42
	for _, v := range p.NodeLst {
//line views/ybs/admin_node.qtpl:42
		qw422016.N().S(`
        <li class="bot-line">
            `)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().DUL(v.ID)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().S(` - <a href="/admin/node?id=`)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().DUL(v.ID)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().S(`">`)
//line views/ybs/admin_node.qtpl:44
		qw422016.E().S(v.Name)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().S(`</a> - `)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().D(v.Score)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().S(` - `)
//line views/ybs/admin_node.qtpl:44
		qw422016.E().S(v.About)
//line views/ybs/admin_node.qtpl:44
		qw422016.N().S(`
        </li>
        `)
//line views/ybs/admin_node.qtpl:46
	}
//line views/ybs/admin_node.qtpl:46
	qw422016.N().S(`
    </ul>


    </div>
</div>

`)
//line views/ybs/admin_node.qtpl:53
}

//line views/ybs/admin_node.qtpl:53
func (p *AdminNode) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/admin_node.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/admin_node.qtpl:53
	p.StreamMainBody(qw422016)
//line views/ybs/admin_node.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/admin_node.qtpl:53
}

//line views/ybs/admin_node.qtpl:53
func (p *AdminNode) MainBody() string {
//line views/ybs/admin_node.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/admin_node.qtpl:53
	p.WriteMainBody(qb422016)
//line views/ybs/admin_node.qtpl:53
	qs422016 := string(qb422016.B)
//line views/ybs/admin_node.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/admin_node.qtpl:53
	return qs422016
//line views/ybs/admin_node.qtpl:53
}
