// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// base.qtpl

//line views/ybs/base.qtpl:2
package ybs

//line views/ybs/base.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/base.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/base.qtpl:3
type Page interface {
//line views/ybs/base.qtpl:3
	Header() string
//line views/ybs/base.qtpl:3
	StreamHeader(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteHeader(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
	Banner() string
//line views/ybs/base.qtpl:3
	StreamBanner(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteBanner(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
	MainBodyNav() string
//line views/ybs/base.qtpl:3
	StreamMainBodyNav(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteMainBodyNav(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
	MainBody() string
//line views/ybs/base.qtpl:3
	StreamMainBody(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteMainBody(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
	Aside() string
//line views/ybs/base.qtpl:3
	StreamAside(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteAside(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
	Footer() string
//line views/ybs/base.qtpl:3
	StreamFooter(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:3
	WriteFooter(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:3
}

//line views/ybs/base.qtpl:13
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line views/ybs/base.qtpl:13
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    `)
//line views/ybs/base.qtpl:18
	p.StreamHeader(qw422016)
//line views/ybs/base.qtpl:18
	qw422016.N().S(`
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" />
    <meta name="mobile-web-app-capable" content="yes">
    <meta content="black" name="apple-mobile-web-app-status-bar-style" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="shortcut icon" href="/static/favicon.png" type="image/x-icon" />
</head>

<body>
<a name="top"></a>

<!-- ===== 顶部导航 ===== -->
<header class="wk-header">
    <div class="wk-header-inner">
        `)
//line views/ybs/base.qtpl:33
	p.StreamBanner(qw422016)
//line views/ybs/base.qtpl:33
	qw422016.N().S(`
    </div>
</header>

<!-- ===== 三栏主体 ===== -->
<div class="wk-shell">
    <!-- 左栏：导航 -->
    <aside class="wk-sidebar">
        `)
//line views/ybs/base.qtpl:41
	p.StreamMainBodyNav(qw422016)
//line views/ybs/base.qtpl:41
	qw422016.N().S(`
    </aside>

    <!-- 中栏：内容 -->
    <main class="wk-main">
        <div class="wk-content">
            `)
//line views/ybs/base.qtpl:47
	p.StreamMainBody(qw422016)
//line views/ybs/base.qtpl:47
	qw422016.N().S(`
        </div>
    </main>

    <!-- 右栏：侧边栏 -->
    <aside class="wk-toc-col">
        `)
//line views/ybs/base.qtpl:53
	p.StreamAside(qw422016)
//line views/ybs/base.qtpl:53
	qw422016.N().S(`
    </aside>
</div>

<button class="wk-top" id="go-to-top" aria-label="回到顶部">▲</button>

<footer role="contentinfo" class="wk-foot">
    `)
//line views/ybs/base.qtpl:60
	p.StreamFooter(qw422016)
//line views/ybs/base.qtpl:60
	qw422016.N().S(`
</footer>

<script>
/* ===== 回到顶部 ===== */
(function () {
    var btn = document.getElementById('go-to-top');
    if (!btn) return;
    window.addEventListener('scroll', function () {
        btn.classList.toggle('visible', (window.scrollY || document.documentElement.scrollTop) > 600);
    }, { passive: true });
    btn.addEventListener('click', function () {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    });
})();
</script>
</body>
</html>
`)
//line views/ybs/base.qtpl:78
}

//line views/ybs/base.qtpl:78
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line views/ybs/base.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:78
	StreamPageTemplate(qw422016, p)
//line views/ybs/base.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:78
}

//line views/ybs/base.qtpl:78
func PageTemplate(p Page) string {
//line views/ybs/base.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:78
	WritePageTemplate(qb422016, p)
//line views/ybs/base.qtpl:78
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:78
	return qs422016
//line views/ybs/base.qtpl:78
}

//line views/ybs/base.qtpl:81
func (p *BasePage) StreamHeader(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:81
	qw422016.N().S(`
<title>`)
//line views/ybs/base.qtpl:82
	qw422016.E().S(p.Title)
//line views/ybs/base.qtpl:82
	qw422016.N().S(`</title>
<meta name="description" content="`)
//line views/ybs/base.qtpl:83
	qw422016.E().S(p.Description)
//line views/ybs/base.qtpl:83
	qw422016.N().S(`">
<meta name="keywords" content="`)
//line views/ybs/base.qtpl:84
	qw422016.E().S(p.Keywords)
//line views/ybs/base.qtpl:84
	qw422016.N().S(`">
<link rel="canonical" href="`)
//line views/ybs/base.qtpl:85
	qw422016.E().S(p.Canonical)
//line views/ybs/base.qtpl:85
	qw422016.N().S(`">
<link href="/feed" rel="alternate" title="`)
//line views/ybs/base.qtpl:86
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:86
	qw422016.N().S(`" type="application/atom+xml">

<style>
/* ===== Wiki 风格全局样式 ===== */
:root {
  --wk-bg:            #ffffff;
  --wk-bg-soft:       #f7f8fa;
  --wk-bg-sidebar:    #fbfbfc;
  --wk-border:        #e6e8eb;
  --wk-border-strong: #d6dae0;
  --wk-text:          #1f2328;
  --wk-text-2:        #4a5158;
  --wk-text-muted:    #7a838d;
  --wk-accent:        #3b82f6;
  --wk-accent-soft:   #eff6ff;
  --wk-tag:           #8b5cf6;
  --wk-tag-soft:      #f5f3ff;
  --wk-user:          #0ea5e9;
  --wk-user-soft:     #f0f9ff;
  --wk-warn:          #f59e0b;
  --wk-warn-soft:     #fffbeb;
  --wk-warn-border:   #fde68a;
  --wk-danger:        #ef4444;
  --wk-danger-soft:   #fef2f2;
  --wk-success:       #22c55e;
  --wk-success-soft:  #f0fdf4;
  --wk-link:          #0969da;
  --wk-code-bg:       #f6f8fa;
  --wk-radius:        8px;
  --wk-radius-sm:     6px;
  --wk-header-h:      58px;
  --wk-sidebar-w:     264px;
  --wk-toc-w:         236px;
  --wk-content-max:   860px;
  --wk-font:          -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
                      "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue",
                      Helvetica, Arial, sans-serif;
  --wk-mono:          ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas,
                      "Liberation Mono", monospace;
}

@media (prefers-color-scheme: dark) {
  :root {
    --wk-bg:            #14161a;
    --wk-bg-soft:       #1a1d22;
    --wk-bg-sidebar:    #17191e;
    --wk-border:        #2a2e35;
    --wk-border-strong: #363b44;
    --wk-text:          #e6e8eb;
    --wk-text-2:        #b6bdc6;
    --wk-text-muted:    #8b939e;
    --wk-accent:        #60a5fa;
    --wk-accent-soft:   #1c2836;
    --wk-tag:           #a78bfa;
    --wk-tag-soft:      #241c36;
    --wk-user:          #38bdf8;
    --wk-user-soft:     #14293a;
    --wk-warn:          #fbbf24;
    --wk-warn-soft:     #2a2008;
    --wk-warn-border:   #5a4318;
    --wk-danger:        #f87171;
    --wk-danger-soft:   #2a1518;
    --wk-success:       #4ade80;
    --wk-success-soft:  #14291d;
    --wk-link:          #6cb6ff;
    --wk-code-bg:       #1c1f24;
  }
}

* { box-sizing: border-box; }
html { scroll-behavior: smooth; scroll-padding-top: calc(var(--wk-header-h) + 20px); }

body {
  margin: 0;
  font-family: var(--wk-font);
  font-size: 16.5px;
  line-height: 1.75;
  color: var(--wk-text);
  background: var(--wk-bg);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

a { color: var(--wk-link); text-decoration: none; }
a:hover { text-decoration: underline; }

/* ===== 顶部导航 ===== */
.wk-header {
  position: sticky; top: 0; z-index: 60;
  height: var(--wk-header-h);
  background: color-mix(in srgb, var(--wk-bg) 88%, transparent);
  backdrop-filter: saturate(180%) blur(12px);
  -webkit-backdrop-filter: saturate(180%) blur(12px);
  border-bottom: 1px solid var(--wk-border);
}
.wk-header-inner {
  height: 100%; display: flex; align-items: center; gap: 16px;
  padding: 0 20px; max-width: 1680px; margin: 0 auto;
}
.wk-brand {
  display: flex; align-items: center; gap: 10px;
  font-weight: 700; font-size: 16px;
  color: var(--wk-text); text-decoration: none !important; white-space: nowrap;
}
.wk-brand:hover { color: var(--wk-accent); }
.wk-brand-mark {
  width: 28px; height: 28px; display: grid; place-items: center;
  border-radius: 7px; background: linear-gradient(135deg, #3b82f6, #8b5cf6);
  color: #fff; font-size: 14px; font-weight: 800; letter-spacing: -.5px;
}
.wk-search { flex: 1; max-width: 420px; position: relative; }
.wk-search input {
  width: 100%; height: 36px; padding: 0 12px 0 34px;
  border: 1px solid var(--wk-border-strong); border-radius: 7px;
  background: var(--wk-bg-soft); color: var(--wk-text);
  font-size: 14.5px; outline: none;
  transition: border-color .15s, background .15s, box-shadow .15s;
}
.wk-search input::placeholder { color: var(--wk-text-muted); }
.wk-search input:focus {
  border-color: var(--wk-accent); background: var(--wk-bg);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--wk-accent) 18%, transparent);
}
.wk-search svg {
  position: absolute; left: 11px; top: 50%; transform: translateY(-50%);
  width: 15px; height: 15px; color: var(--wk-text-muted); pointer-events: none;
}
.wk-header-actions { margin-left: auto; display: flex; align-items: center; gap: 8px; }
.wk-avatar { width: 30px; height: 30px; border-radius: 50%; object-fit: cover; border: 1px solid var(--wk-border); display: block; }
.wk-btn-ghost {
  display: inline-flex; align-items: center; gap: 6px;
  height: 32px; padding: 0 12px; border-radius: 7px;
  border: 1px solid var(--wk-border-strong); background: transparent;
  color: var(--wk-text-2); font-size: 14px; cursor: pointer;
  text-decoration: none !important; position: relative;
  transition: background .15s, border-color .15s, color .15s;
}
.wk-btn-ghost:hover { background: var(--wk-bg-soft); border-color: var(--wk-accent); color: var(--wk-accent); }
.wk-btn-primary {
  display: inline-flex; align-items: center; gap: 6px;
  height: 32px; padding: 0 14px; border-radius: 7px;
  border: 1px solid var(--wk-accent); background: var(--wk-accent);
  color: #fff !important; font-size: 14px; font-weight: 600;
  cursor: pointer; text-decoration: none !important;
  transition: background .15s, transform .1s;
}
.wk-btn-primary:hover { background: color-mix(in srgb, var(--wk-accent) 85%, #000); border-color: color-mix(in srgb, var(--wk-accent) 85%, #000); }
.wk-btn-primary:active { transform: translateY(1px); }

/* 角标 */
.wk-badge-count {
  position: absolute; top: -5px; right: -6px;
  min-width: 17px; height: 17px; padding: 0 5px;
  display: inline-flex; align-items: center; justify-content: center;
  border-radius: 999px; background: var(--wk-danger); color: #fff;
  font-size: 10.5px; font-weight: 700; font-variant-numeric: tabular-nums;
  border: 2px solid var(--wk-bg); line-height: 1;
}
.wk-badge-count.warn { background: var(--wk-warn); }
.wk-btn-ghost.has-unread { border-color: color-mix(in srgb, var(--wk-danger) 34%, transparent); background: var(--wk-danger-soft); color: var(--wk-danger); }
.wk-btn-ghost.has-unread:hover { border-color: var(--wk-danger); background: color-mix(in srgb, var(--wk-danger) 12%, transparent); color: var(--wk-danger); }
.wk-btn-ghost.has-review { border-color: var(--wk-warn-border); background: var(--wk-warn-soft); color: var(--wk-warn); }
.wk-btn-ghost.has-review:hover { border-color: var(--wk-warn); background: color-mix(in srgb, var(--wk-warn) 12%, transparent); color: var(--wk-warn); }

/* ===== 三栏布局 ===== */
.wk-shell {
  display: grid;
  grid-template-columns: var(--wk-sidebar-w) minmax(0, 1fr) var(--wk-toc-w);
  gap: 0; max-width: 1680px; margin: 0 auto;
  min-height: calc(100vh - var(--wk-header-h));
}

/* ===== 左栏导航 ===== */
.wk-sidebar {
  border-right: 1px solid var(--wk-border); background: var(--wk-bg-sidebar);
  padding: 22px 14px 60px;
  position: sticky; top: var(--wk-header-h);
  height: calc(100vh - var(--wk-header-h));
  overflow-y: auto; overscroll-behavior: contain;
}
.wk-sidebar::-webkit-scrollbar { width: 8px; }
.wk-sidebar::-webkit-scrollbar-thumb { background: var(--wk-border-strong); border-radius: 4px; }
.wk-side-title {
  display: flex; align-items: center; gap: 7px;
  font-size: 12px; font-weight: 700; letter-spacing: .07em;
  text-transform: uppercase; color: var(--wk-text-muted);
  padding: 0 10px; margin: 0 0 8px;
}
.wk-side-group { margin-bottom: 26px; }
.wk-navlist { list-style: none; margin: 0; padding: 0; }
.wk-navlist li { margin: 0; }
.wk-navlist a {
  display: flex; align-items: center; gap: 8px;
  padding: 6px 10px; border-radius: var(--wk-radius-sm);
  font-size: 15px; line-height: 1.45; color: var(--wk-text-2);
  text-decoration: none !important; white-space: nowrap;
  overflow: hidden; text-overflow: ellipsis;
  transition: background .12s, color .12s;
}
.wk-navlist a:hover { background: color-mix(in srgb, var(--wk-accent) 9%, transparent); color: var(--wk-accent); }
.wk-navlist a.is-active { background: var(--wk-accent-soft); color: var(--wk-accent); font-weight: 600; box-shadow: inset 3px 0 0 var(--wk-accent); }
.wk-navlist a .lbl { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; }
.wk-navlist .wk-count { font-size: 12px; color: var(--wk-text-muted); font-variant-numeric: tabular-nums; }
.wk-navlist .wk-pill {
  display: inline-flex; align-items: center; justify-content: center;
  min-width: 20px; height: 18px; padding: 0 6px;
  border-radius: 999px; font-size: 10.5px; font-weight: 700;
  font-variant-numeric: tabular-nums;
}
.wk-navlist .wk-pill.danger { background: var(--wk-danger-soft); border: 1px solid color-mix(in srgb, var(--wk-danger) 30%, transparent); color: var(--wk-danger); }
.wk-navlist .wk-pill.warn { background: var(--wk-warn-soft); border: 1px solid var(--wk-warn-border); color: var(--wk-warn); }
.wk-navlist a.is-unread { background: var(--wk-danger-soft); color: var(--wk-danger); font-weight: 600; border: 1px solid color-mix(in srgb, var(--wk-danger) 20%, transparent); }
.wk-navlist a.is-review { background: var(--wk-warn-soft); color: var(--wk-warn); font-weight: 600; border: 1px solid var(--wk-warn-border); }

/* ===== 中栏内容 ===== */
.wk-main { min-width: 0; padding: 0 0 80px; }
.wk-content { max-width: var(--wk-content-max); margin: 0 auto; padding: 28px 40px 0; }

/* ===== 右栏 ===== */
.wk-toc-col {
  border-left: 1px solid var(--wk-border); background: var(--wk-bg);
  padding: 26px 16px 60px;
  position: sticky; top: var(--wk-header-h);
  height: calc(100vh - var(--wk-header-h));
  overflow-y: auto; overscroll-behavior: contain;
}
.wk-toc-title {
  font-size: 12px; font-weight: 700; letter-spacing: .07em;
  text-transform: uppercase; color: var(--wk-text-muted);
  margin: 0 0 10px; padding-left: 10px;
}
.wk-toc-title.mt { margin-top: 26px; }
.wk-info-card {
  border: 1px solid var(--wk-border); border-radius: var(--wk-radius);
  background: var(--wk-bg-soft); padding: 14px 15px; margin-bottom: 22px;
}
.wk-info-card h4 {
  margin: 0 0 11px; font-size: 12px; font-weight: 700;
  letter-spacing: .07em; text-transform: uppercase; color: var(--wk-text-muted);
}
.wk-info-row { display: flex; align-items: baseline; gap: 8px; font-size: 14px; line-height: 1.7; color: var(--wk-text-2); }
.wk-info-row + .wk-info-row { margin-top: 5px; }
.wk-info-row .k { flex: 0 0 40px; color: var(--wk-text-muted); }
.wk-info-row .v { flex: 1; min-width: 0; word-break: break-word; }
.wk-info-row .v a { color: var(--wk-text-2); }
.wk-info-row .v a:hover { color: var(--wk-accent); }
.wk-stat-bar { display: flex; flex-direction: column; gap: 12px; }
.wk-stat-item { font-size: 12.5px; }
.wk-stat-item .top { display: flex; justify-content: space-between; margin-bottom: 4px; color: var(--wk-text-2); }
.wk-stat-item .top b { color: var(--wk-text); font-variant-numeric: tabular-nums; font-weight: 650; }
.wk-stat-item .track { height: 6px; border-radius: 999px; background: var(--wk-bg-soft); border: 1px solid var(--wk-border); overflow: hidden; }
.wk-stat-item .fill { height: 100%; border-radius: 999px; background: linear-gradient(90deg, #3b82f6, #8b5cf6); }
.wk-rel-list { list-style: none; margin: 0; padding: 0; }
.wk-rel-list li { margin: 0 0 2px; }
.wk-rel-list a {
  display: block; padding: 5px 10px; border-radius: var(--wk-radius-sm);
  font-size: 14px; line-height: 1.5; color: var(--wk-text-2);
  text-decoration: none !important; transition: background .12s, color .12s;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
.wk-rel-list a:hover { background: var(--wk-accent-soft); color: var(--wk-accent); }
.wk-recent-comments { list-style: none; margin: 0; padding: 0; }
.wk-recent-comments li { display: flex; gap: 9px; padding: 8px 10px; border-radius: var(--wk-radius-sm); font-size: 14px; line-height: 1.5; transition: background .12s; }
.wk-recent-comments li:hover { background: var(--wk-bg-soft); }
.wk-recent-comments img { flex: 0 0 auto; width: 20px; height: 20px; border-radius: 50%; border: 1px solid var(--wk-border); }
.wk-recent-comments a { color: var(--wk-text-2); display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; text-decoration: none !important; }
.wk-recent-comments a:hover { color: var(--wk-accent); }
.wk-links { list-style: none; margin: 0; padding: 0; }
.wk-links li { margin: 0 0 2px; }
.wk-links a { display: flex; align-items: center; gap: 7px; padding: 6px 10px; border-radius: var(--wk-radius-sm); font-size: 14px; color: var(--wk-text-2); text-decoration: none !important; transition: background .12s, color .12s; }
.wk-links a:hover { background: var(--wk-bg-soft); color: var(--wk-accent); }
.wk-links a::before { content: "↗"; font-size: 11px; opacity: .55; }

/* ===== 标签云 ===== */
.wk-tagcloud { display: flex; flex-wrap: wrap; gap: 6px; padding: 0 6px; }
.wk-tagcloud a { display: inline-flex; align-items: center; gap: 4px; padding: 3px 9px; border-radius: 999px; border: 1px solid var(--wk-border); background: var(--wk-bg); color: var(--wk-text-2); font-size: 13.5px; text-decoration: none !important; transition: all .12s; }
.wk-tagcloud a:hover { border-color: var(--wk-tag); color: var(--wk-tag); background: var(--wk-tag-soft); }
.wk-tagcloud a .n { font-size: 12px; color: var(--wk-text-muted); font-variant-numeric: tabular-nums; }

/* ===== 回到顶部 ===== */
.wk-top {
  position: fixed; right: 26px; bottom: 26px; width: 40px; height: 40px;
  display: grid; place-items: center; border-radius: 50%;
  border: 1px solid var(--wk-border-strong); background: var(--wk-bg);
  color: var(--wk-text-2); font-size: 15px; cursor: pointer;
  opacity: 0; visibility: hidden; transform: translateY(8px);
  transition: opacity .2s, transform .2s, visibility .2s, color .15s, border-color .15s;
  box-shadow: 0 4px 14px rgba(0,0,0,.09); z-index: 50;
}
.wk-top.visible { opacity: 1; visibility: visible; transform: translateY(0); }
.wk-top:hover { color: var(--wk-accent); border-color: var(--wk-accent); }

/* ===== 页脚 ===== */
.wk-foot { border-top: 1px solid var(--wk-border); padding: 26px 20px; text-align: center; color: var(--wk-text-muted); font-size: 12.5px; }
.wk-foot a { color: var(--wk-text-muted); }
.wk-foot a:hover { color: var(--wk-accent); }

/* ===== 响应式 ===== */
@media (max-width: 1280px) {
  :root { --wk-toc-w: 0px; }
  .wk-shell { grid-template-columns: var(--wk-sidebar-w) minmax(0, 1fr); }
  .wk-toc-col { display: none; }
}
@media (max-width: 960px) {
  :root { --wk-sidebar-w: 0px; }
  .wk-shell { grid-template-columns: minmax(0, 1fr); }
  .wk-sidebar { display: none; }
  .wk-content { padding-left: 22px; padding-right: 22px; }
}
@media (max-width: 640px) {
  .wk-header-inner { padding: 0 14px; gap: 10px; }
  .wk-search { max-width: none; }
  .wk-header-actions .wk-label { display: none; }
  .wk-content { padding-left: 16px; padding-right: 16px; }
  .wk-top { right: 14px; bottom: 14px; }
}

/* ===== 页面内容组件（所有页面共用）===== */
.wk-breadcrumb { display: flex; align-items: center; flex-wrap: wrap; gap: 6px; font-size: 12.5px; color: var(--wk-text-muted); margin-bottom: 18px; }
.wk-breadcrumb a { color: var(--wk-text-muted); }
.wk-breadcrumb a:hover { color: var(--wk-accent); }
.wk-breadcrumb .sep { opacity: .5; }
.wk-breadcrumb .current { color: var(--wk-text-2); }

.wk-page-head { display: flex; align-items: flex-start; gap: 16px; padding-bottom: 20px; border-bottom: 1px solid var(--wk-border); margin-bottom: 22px; }
.wk-page-head .ph-icon { flex: 0 0 auto; width: 44px; height: 44px; display: grid; place-items: center; border-radius: 12px; font-size: 20px; background: linear-gradient(135deg, var(--wk-accent-soft), var(--wk-tag-soft)); border: 1px solid var(--wk-border); }
.wk-page-title { margin: 0 0 6px; font-size: 24px; font-weight: 700; line-height: 1.3; letter-spacing: -.02em; color: var(--wk-text); }
.wk-page-desc { margin: 0; font-size: 13.5px; color: var(--wk-text-muted); line-height: 1.6; }

.wk-list { list-style: none; margin: 0; padding: 0; }
.wk-item { display: flex; gap: 14px; padding: 18px 14px; margin: 0 -14px; border-radius: var(--wk-radius); border-bottom: 1px solid var(--wk-border); transition: background .13s; }
.wk-item:last-child { border-bottom: 0; }
.wk-item:hover { background: var(--wk-bg-soft); border-bottom-color: transparent; }
.wk-item-avatar { flex: 0 0 auto; width: 40px; height: 40px; border-radius: 9px; overflow: hidden; border: 1px solid var(--wk-border); background: var(--wk-bg-soft); }
.wk-item-avatar img { width: 100%; height: 100%; object-fit: cover; display: block; }
.wk-item-body { flex: 1; min-width: 0; }
.wk-item-title { display: inline-block; font-size: 16px; font-weight: 620; line-height: 1.45; color: var(--wk-text); text-decoration: none !important; margin: 0 0 6px; transition: color .12s; word-break: break-word; }
.wk-item-title:hover { color: var(--wk-accent); }
.wk-item-meta { display: flex; flex-wrap: wrap; align-items: center; gap: 12px; font-size: 12.5px; color: var(--wk-text-muted); line-height: 1.6; }
.wk-item-meta .mi { display: inline-flex; align-items: center; gap: 5px; }
.wk-item-meta a { color: var(--wk-text-muted); }
.wk-item-meta a:hover { color: var(--wk-accent); }
.wk-item-meta time { font-variant-numeric: tabular-nums; }

.wk-chip { display: inline-flex; align-items: center; padding: 1px 8px; border-radius: 999px; font-size: 11.5px; font-weight: 600; background: var(--wk-bg-soft); border: 1px solid var(--wk-border); color: var(--wk-text-2); text-decoration: none !important; transition: all .12s; }
.wk-chip:hover { border-color: var(--wk-accent); color: var(--wk-accent); background: var(--wk-accent-soft); }

.wk-comment-pill { display: inline-flex; align-items: center; gap: 4px; padding: 1px 8px; border-radius: 999px; background: var(--wk-accent-soft); border: 1px solid color-mix(in srgb, var(--wk-accent) 24%, transparent); color: var(--wk-accent) !important; font-size: 11.5px; font-weight: 600; font-variant-numeric: tabular-nums; text-decoration: none !important; transition: background .13s; }
.wk-comment-pill:hover { background: color-mix(in srgb, var(--wk-accent) 16%, transparent); }
.wk-comment-pill.is-zero { background: var(--wk-bg-soft); border-color: var(--wk-border); color: var(--wk-text-muted) !important; font-weight: 500; }
.wk-comment-pill.is-hot { background: #fef2f2; border-color: #fecaca; color: #dc2626 !important; }

.wk-toolbar { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; padding: 12px 0 4px; margin-bottom: 4px; }
.wk-toolbar-label { font-size: 12px; font-weight: 600; letter-spacing: .06em; text-transform: uppercase; color: var(--wk-text-muted); }
.wk-seg { display: inline-flex; padding: 2px; border-radius: 8px; background: var(--wk-bg-soft); border: 1px solid var(--wk-border); }
.wk-seg button { border: 0; background: transparent; font-family: var(--wk-font); font-size: 12.5px; color: var(--wk-text-2); padding: 5px 12px; border-radius: 6px; cursor: pointer; transition: background .13s, color .13s; }
.wk-seg button:hover { color: var(--wk-accent); }
.wk-seg button.is-active { background: var(--wk-bg); color: var(--wk-accent); font-weight: 600; box-shadow: 0 1px 3px rgba(0,0,0,.07); }
.wk-toolbar .wk-spacer { margin-left: auto; }

.wk-pagination { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin: 34px 0 0; padding-top: 22px; border-top: 1px solid var(--wk-border); }
.wk-pagination .wk-page-info { font-size: 13px; color: var(--wk-text-muted); }
.wk-pagination .wk-page-info b { color: var(--wk-text); font-variant-numeric: tabular-nums; }
.wk-page-btn { display: inline-flex; align-items: center; gap: 6px; height: 36px; padding: 0 16px; border-radius: 8px; border: 1px solid var(--wk-border-strong); background: var(--wk-bg); color: var(--wk-text-2); font-size: 13.5px; font-weight: 500; text-decoration: none !important; transition: all .14s; }
.wk-page-btn:hover { border-color: var(--wk-accent); color: var(--wk-accent); background: var(--wk-accent-soft); }
.wk-page-btn.is-disabled { opacity: .4; pointer-events: none; }

/* 代码块复制按钮 */
.copy-btn { position: absolute; top: 9px; right: 9px; padding: 3px 10px; font-size: 11.5px; font-family: var(--wk-font); color: var(--wk-text-muted); background: color-mix(in srgb, var(--wk-bg) 90%, transparent); border: 1px solid var(--wk-border-strong); border-radius: 6px; cursor: pointer; opacity: 0; transition: opacity .15s, background .15s, color .15s; z-index: 2; }
.pre-container:hover .copy-btn { opacity: 1; }
.copy-btn:hover { color: var(--wk-accent); border-color: var(--wk-accent); background: var(--wk-bg); }
.copy-btn.copied { color: #16a34a; border-color: #16a34a; opacity: 1; }
pre { position: relative; }
</style>

<script src="/static/js/main.js?v=`)
//line views/ybs/base.qtpl:461
	qw422016.E().S(p.SiteCf.SelfHash)
//line views/ybs/base.qtpl:461
	qw422016.N().S(`"></script>
<script src="/static/js/md5.min.js" type="text/javascript"></script>

`)
//line views/ybs/base.qtpl:464
	if len(p.JsonLd) > 0 {
//line views/ybs/base.qtpl:464
		qw422016.N().S(`
<script type="application/ld+json">
`)
//line views/ybs/base.qtpl:466
		qw422016.N().S(p.JsonLd)
//line views/ybs/base.qtpl:466
		qw422016.N().S(`
</script>
`)
//line views/ybs/base.qtpl:468
	}
//line views/ybs/base.qtpl:468
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:470
	if p.ShowAutoAd && len(p.SiteCf.GoogleAutoAdJs) > 0 {
//line views/ybs/base.qtpl:470
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:471
		qw422016.N().S(p.SiteCf.GoogleAutoAdJs)
//line views/ybs/base.qtpl:471
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:472
	}
//line views/ybs/base.qtpl:472
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:474
	if len(p.SiteCf.HeaderPartCon) > 0 {
//line views/ybs/base.qtpl:474
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:475
		qw422016.N().S(p.SiteCf.HeaderPartCon)
//line views/ybs/base.qtpl:475
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:476
	}
//line views/ybs/base.qtpl:476
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:477
}

//line views/ybs/base.qtpl:477
func (p *BasePage) WriteHeader(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:477
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:477
	p.StreamHeader(qw422016)
//line views/ybs/base.qtpl:477
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:477
}

//line views/ybs/base.qtpl:477
func (p *BasePage) Header() string {
//line views/ybs/base.qtpl:477
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:477
	p.WriteHeader(qb422016)
//line views/ybs/base.qtpl:477
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:477
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:477
	return qs422016
//line views/ybs/base.qtpl:477
}

//line views/ybs/base.qtpl:480
func (p *BasePage) StreamBanner(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:480
	qw422016.N().S(`
<a href="/" class="wk-brand">
    <span class="wk-brand-mark">G</span>
    <span>`)
//line views/ybs/base.qtpl:483
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:483
	qw422016.N().S(`</span>
</a>

<div class="wk-search">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
         stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <circle cx="11" cy="11" r="7"></circle>
        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
    </svg>
    <form action="/q" method="get">
        <input type="text" name="q" placeholder="搜索文档、标签或内容…" autocomplete="off" />
    </form>
</div>

<div class="wk-header-actions">
`)
//line views/ybs/base.qtpl:498
	if p.CurrentUser.ID > 0 {
//line views/ybs/base.qtpl:498
		qw422016.N().S(`
    `)
//line views/ybs/base.qtpl:499
		if p.HasMsg {
//line views/ybs/base.qtpl:499
			qw422016.N().S(`
    <a class="wk-btn-ghost has-unread" href="/my/msg" title="未读信息">
        <span>✉</span><span class="wk-label">未读信息</span>
        `)
//line views/ybs/base.qtpl:502
			if p.MsgNum > 0 {
//line views/ybs/base.qtpl:502
				qw422016.N().S(`<span class="wk-badge-count">`)
//line views/ybs/base.qtpl:502
				qw422016.N().D(p.MsgNum)
//line views/ybs/base.qtpl:502
				qw422016.N().S(`</span>`)
//line views/ybs/base.qtpl:502
			}
//line views/ybs/base.qtpl:502
			qw422016.N().S(`
    </a>
    `)
//line views/ybs/base.qtpl:504
		}
//line views/ybs/base.qtpl:504
		qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:506
		if p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:506
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:507
			if p.HasTopicReview {
//line views/ybs/base.qtpl:507
				qw422016.N().S(`
        <a class="wk-btn-ghost has-review" href="/admin/topic/review" title="待审帖子">
            <span>📝</span><span class="wk-label">待审帖子</span>
            `)
//line views/ybs/base.qtpl:510
				if p.TopicReviewNum > 0 {
//line views/ybs/base.qtpl:510
					qw422016.N().S(`<span class="wk-badge-count warn">`)
//line views/ybs/base.qtpl:510
					qw422016.N().D(p.TopicReviewNum)
//line views/ybs/base.qtpl:510
					qw422016.N().S(`</span>`)
//line views/ybs/base.qtpl:510
				}
//line views/ybs/base.qtpl:510
				qw422016.N().S(`
        </a>
        `)
//line views/ybs/base.qtpl:512
			}
//line views/ybs/base.qtpl:512
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:513
			if p.HasReplyReview {
//line views/ybs/base.qtpl:513
				qw422016.N().S(`
        <a class="wk-btn-ghost has-review" href="/admin/comment/review" title="待审评论">
            <span>💬</span><span class="wk-label">待审评论</span>
            `)
//line views/ybs/base.qtpl:516
				if p.ReplyReviewNum > 0 {
//line views/ybs/base.qtpl:516
					qw422016.N().S(`<span class="wk-badge-count warn">`)
//line views/ybs/base.qtpl:516
					qw422016.N().D(p.ReplyReviewNum)
//line views/ybs/base.qtpl:516
					qw422016.N().S(`</span>`)
//line views/ybs/base.qtpl:516
				}
//line views/ybs/base.qtpl:516
				qw422016.N().S(`
        </a>
        `)
//line views/ybs/base.qtpl:518
			}
//line views/ybs/base.qtpl:518
			qw422016.N().S(`
    `)
//line views/ybs/base.qtpl:519
		}
//line views/ybs/base.qtpl:519
		qw422016.N().S(`

    <a class="wk-btn-primary" href="/topic/add?nid=`)
//line views/ybs/base.qtpl:521
		qw422016.N().DUL(p.DefaultNode.ID)
//line views/ybs/base.qtpl:521
		qw422016.N().S(`">
        <span>＋</span><span class="wk-label">发帖</span>
    </a>
    <a href="/member/`)
//line views/ybs/base.qtpl:524
		qw422016.N().DUL(p.CurrentUser.ID)
//line views/ybs/base.qtpl:524
		qw422016.N().S(`" title="`)
//line views/ybs/base.qtpl:524
		qw422016.E().S(p.CurrentUser.Name)
//line views/ybs/base.qtpl:524
		qw422016.N().S(`">
        <img class="wk-avatar" src="/avatar/`)
//line views/ybs/base.qtpl:525
		qw422016.N().DUL(p.CurrentUser.ID)
//line views/ybs/base.qtpl:525
		qw422016.N().S(`.jpg" alt="`)
//line views/ybs/base.qtpl:525
		qw422016.E().S(p.CurrentUser.Name)
//line views/ybs/base.qtpl:525
		qw422016.N().S(` avatar">
    </a>
`)
//line views/ybs/base.qtpl:527
	} else {
//line views/ybs/base.qtpl:527
		qw422016.N().S(`
    <a class="wk-btn-ghost" href="/login" rel="nofollow">登录</a>
    <a class="wk-btn-primary" href="/register" rel="nofollow">注册</a>
`)
//line views/ybs/base.qtpl:530
	}
//line views/ybs/base.qtpl:530
	qw422016.N().S(`
</div>
`)
//line views/ybs/base.qtpl:532
}

//line views/ybs/base.qtpl:532
func (p *BasePage) WriteBanner(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:532
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:532
	p.StreamBanner(qw422016)
//line views/ybs/base.qtpl:532
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:532
}

//line views/ybs/base.qtpl:532
func (p *BasePage) Banner() string {
//line views/ybs/base.qtpl:532
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:532
	p.WriteBanner(qb422016)
//line views/ybs/base.qtpl:532
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:532
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:532
	return qs422016
//line views/ybs/base.qtpl:532
}

// MainBodyNav：左栏导航

//line views/ybs/base.qtpl:536
func (p *BasePage) StreamMainBodyNav(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:536
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:537
	if p.CurrentUser.ID > 0 {
//line views/ybs/base.qtpl:537
		qw422016.N().S(`
    `)
//line views/ybs/base.qtpl:538
		if p.HasMsg || p.HasTopicReview || p.HasReplyReview {
//line views/ybs/base.qtpl:538
			qw422016.N().S(`
    <div class="wk-side-group">
        <h3 class="wk-side-title"><span>🔔</span> 待我处理</h3>
        <ul class="wk-navlist">
            `)
//line views/ybs/base.qtpl:542
			if p.HasMsg {
//line views/ybs/base.qtpl:542
				qw422016.N().S(`
            <li>
                <a href="/my/msg" class="is-unread">
                    <span class="lbl">✉ 未读信息</span>
                    <span class="wk-pill danger">`)
//line views/ybs/base.qtpl:546
				qw422016.N().D(p.MsgNum)
//line views/ybs/base.qtpl:546
				qw422016.N().S(`</span>
                </a>
            </li>
            `)
//line views/ybs/base.qtpl:549
			}
//line views/ybs/base.qtpl:549
			qw422016.N().S(`
            `)
//line views/ybs/base.qtpl:550
			if p.HasTopicReview && p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:550
				qw422016.N().S(`
            <li>
                <a href="/admin/topic/review" class="is-review">
                    <span class="lbl">📝 待审帖子</span>
                    <span class="wk-pill warn">`)
//line views/ybs/base.qtpl:554
				qw422016.N().D(p.TopicReviewNum)
//line views/ybs/base.qtpl:554
				qw422016.N().S(`</span>
                </a>
            </li>
            `)
//line views/ybs/base.qtpl:557
			}
//line views/ybs/base.qtpl:557
			qw422016.N().S(`
            `)
//line views/ybs/base.qtpl:558
			if p.HasReplyReview && p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:558
				qw422016.N().S(`
            <li>
                <a href="/admin/comment/review" class="is-review">
                    <span class="lbl">💬 待审评论</span>
                    <span class="wk-pill warn">`)
//line views/ybs/base.qtpl:562
				qw422016.N().D(p.ReplyReviewNum)
//line views/ybs/base.qtpl:562
				qw422016.N().S(`</span>
                </a>
            </li>
            `)
//line views/ybs/base.qtpl:565
			}
//line views/ybs/base.qtpl:565
			qw422016.N().S(`
        </ul>
    </div>
    `)
//line views/ybs/base.qtpl:568
		}
//line views/ybs/base.qtpl:568
		qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:570
		if len(p.NodeLst) > 0 {
//line views/ybs/base.qtpl:570
			qw422016.N().S(`
    <div class="wk-side-group">
        <h3 class="wk-side-title"><span>📁</span> 分类</h3>
        <ul class="wk-navlist">
            `)
//line views/ybs/base.qtpl:574
			for k := range p.NodeLst {
//line views/ybs/base.qtpl:574
				qw422016.N().S(`
            <li>
                <a href="/n/`)
//line views/ybs/base.qtpl:576
				qw422016.N().DUL(p.NodeLst[k].ID)
//line views/ybs/base.qtpl:576
				qw422016.N().S(`" class="`)
//line views/ybs/base.qtpl:576
				if p.DefaultNode.ID == p.NodeLst[k].ID {
//line views/ybs/base.qtpl:576
					qw422016.N().S(`is-active`)
//line views/ybs/base.qtpl:576
				}
//line views/ybs/base.qtpl:576
				qw422016.N().S(`">
                    <span class="lbl">`)
//line views/ybs/base.qtpl:577
				qw422016.E().S(p.NodeLst[k].Name)
//line views/ybs/base.qtpl:577
				qw422016.N().S(`</span>
                    <span class="wk-count">`)
//line views/ybs/base.qtpl:578
				qw422016.N().DUL(p.NodeLst[k].TopicNum)
//line views/ybs/base.qtpl:578
				qw422016.N().S(`</span>
                </a>
            </li>
            `)
//line views/ybs/base.qtpl:581
			}
//line views/ybs/base.qtpl:581
			qw422016.N().S(`
        </ul>
    </div>
    `)
//line views/ybs/base.qtpl:584
		}
//line views/ybs/base.qtpl:584
		qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:586
		if len(p.TagCloud) > 0 {
//line views/ybs/base.qtpl:586
			qw422016.N().S(`
    <div class="wk-side-group">
        <h3 class="wk-side-title"><span>🏷</span> 热门标签</h3>
        <div class="wk-tagcloud">
            `)
//line views/ybs/base.qtpl:590
			for k := range p.TagCloud {
//line views/ybs/base.qtpl:590
				qw422016.N().S(`
            <a href="/tag/`)
//line views/ybs/base.qtpl:591
				qw422016.N().U(p.TagCloud[k].Name)
//line views/ybs/base.qtpl:591
				qw422016.N().S(`">`)
//line views/ybs/base.qtpl:591
				qw422016.E().S(p.TagCloud[k].Name)
//line views/ybs/base.qtpl:591
				qw422016.N().S(` <span class="n">`)
//line views/ybs/base.qtpl:591
				qw422016.N().D(p.TagCloud[k].Size)
//line views/ybs/base.qtpl:591
				qw422016.N().S(`</span></a>
            `)
//line views/ybs/base.qtpl:592
			}
//line views/ybs/base.qtpl:592
			qw422016.N().S(`
        </div>
    </div>
    `)
//line views/ybs/base.qtpl:595
		}
//line views/ybs/base.qtpl:595
		qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:597
		if len(p.RangeTopicLst) > 0 {
//line views/ybs/base.qtpl:597
			qw422016.N().S(`
    <div class="wk-side-group">
        <h3 class="wk-side-title"><span>🕘</span> 最近浏览</h3>
        <ul class="wk-navlist">
            `)
//line views/ybs/base.qtpl:601
			for k := range p.RangeTopicLst {
//line views/ybs/base.qtpl:601
				qw422016.N().S(`
            <li><a href="/t/`)
//line views/ybs/base.qtpl:602
				qw422016.N().DUL(p.RangeTopicLst[k].ID)
//line views/ybs/base.qtpl:602
				qw422016.N().S(`"><span class="lbl">`)
//line views/ybs/base.qtpl:602
				qw422016.E().S(p.RangeTopicLst[k].Title)
//line views/ybs/base.qtpl:602
				qw422016.N().S(`</span></a></li>
            `)
//line views/ybs/base.qtpl:603
			}
//line views/ybs/base.qtpl:603
			qw422016.N().S(`
        </ul>
    </div>
    `)
//line views/ybs/base.qtpl:606
		}
//line views/ybs/base.qtpl:606
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:607
	}
//line views/ybs/base.qtpl:607
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:608
}

//line views/ybs/base.qtpl:608
func (p *BasePage) WriteMainBodyNav(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:608
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:608
	p.StreamMainBodyNav(qw422016)
//line views/ybs/base.qtpl:608
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:608
}

//line views/ybs/base.qtpl:608
func (p *BasePage) MainBodyNav() string {
//line views/ybs/base.qtpl:608
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:608
	p.WriteMainBodyNav(qb422016)
//line views/ybs/base.qtpl:608
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:608
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:608
	return qs422016
//line views/ybs/base.qtpl:608
}

//line views/ybs/base.qtpl:611
func (p *BasePage) StreamAside(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:611
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:612
	if p.HasMsg || p.HasTopicReview || p.HasReplyReview {
//line views/ybs/base.qtpl:612
		qw422016.N().S(`
<div class="wk-todo-card" style="border:1px solid var(--wk-border);border-radius:12px;background:var(--wk-bg-soft);padding:14px 15px;margin-bottom:22px;overflow:hidden;">
    <h4 style="margin:0 0 12px;font-size:11px;font-weight:700;letter-spacing:.07em;text-transform:uppercase;color:var(--wk-text-muted);display:flex;align-items:center;gap:6px;">
        <span>🔔</span> 待我处理
    </h4>
    <ul style="list-style:none;margin:0;padding:0;">
        `)
//line views/ybs/base.qtpl:618
		if p.HasMsg {
//line views/ybs/base.qtpl:618
			qw422016.N().S(`
        <li style="margin-bottom:6px;">
            <a href="/my/msg" style="display:flex;align-items:center;gap:10px;padding:9px 11px;border-radius:8px;border:1px solid color-mix(in srgb, var(--wk-danger) 24%, transparent);background:var(--wk-danger-soft);text-decoration:none;">
                <span style="width:26px;height:26px;display:grid;place-items:center;border-radius:7px;background:var(--wk-bg);border:1px solid color-mix(in srgb, var(--wk-danger) 30%, transparent);font-size:12.5px;">✉</span>
                <span style="flex:1;min-width:0;">
                    <span style="display:block;font-size:13px;font-weight:650;color:var(--wk-danger);line-height:1.35;">未读信息</span>
                    <span style="display:block;font-size:11.5px;color:var(--wk-text-muted);line-height:1.4;margin-top:1px;">被 @ 或回复时提醒</span>
                </span>
                <span style="display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:20px;padding:0 7px;border-radius:999px;background:var(--wk-danger);color:#fff;font-size:11px;font-weight:700;">`)
//line views/ybs/base.qtpl:626
			qw422016.N().D(p.MsgNum)
//line views/ybs/base.qtpl:626
			qw422016.N().S(`</span>
            </a>
        </li>
        `)
//line views/ybs/base.qtpl:629
		}
//line views/ybs/base.qtpl:629
		qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:630
		if p.HasTopicReview && p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:630
			qw422016.N().S(`
        <li style="margin-bottom:6px;">
            <a href="/admin/topic/review" style="display:flex;align-items:center;gap:10px;padding:9px 11px;border-radius:8px;border:1px solid var(--wk-warn-border);background:var(--wk-warn-soft);text-decoration:none;">
                <span style="width:26px;height:26px;display:grid;place-items:center;border-radius:7px;background:var(--wk-bg);border:1px solid var(--wk-warn-border);font-size:12.5px;">📝</span>
                <span style="flex:1;min-width:0;">
                    <span style="display:block;font-size:13px;font-weight:650;color:var(--wk-warn);line-height:1.35;">待审帖子</span>
                    <span style="display:block;font-size:11.5px;color:var(--wk-text-muted);line-height:1.4;margin-top:1px;">新帖等待审核</span>
                </span>
                <span style="display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:20px;padding:0 7px;border-radius:999px;background:var(--wk-warn);color:#fff;font-size:11px;font-weight:700;">`)
//line views/ybs/base.qtpl:638
			qw422016.N().D(p.TopicReviewNum)
//line views/ybs/base.qtpl:638
			qw422016.N().S(`</span>
            </a>
        </li>
        `)
//line views/ybs/base.qtpl:641
		}
//line views/ybs/base.qtpl:641
		qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:642
		if p.HasReplyReview && p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:642
			qw422016.N().S(`
        <li>
            <a href="/admin/comment/review" style="display:flex;align-items:center;gap:10px;padding:9px 11px;border-radius:8px;border:1px solid var(--wk-warn-border);background:var(--wk-warn-soft);text-decoration:none;">
                <span style="width:26px;height:26px;display:grid;place-items:center;border-radius:7px;background:var(--wk-bg);border:1px solid var(--wk-warn-border);font-size:12.5px;">💬</span>
                <span style="flex:1;min-width:0;">
                    <span style="display:block;font-size:13px;font-weight:650;color:var(--wk-warn);line-height:1.35;">待审评论</span>
                    <span style="display:block;font-size:11.5px;color:var(--wk-text-muted);line-height:1.4;margin-top:1px;">评论等待审核</span>
                </span>
                <span style="display:inline-flex;align-items:center;justify-content:center;min-width:22px;height:20px;padding:0 7px;border-radius:999px;background:var(--wk-warn);color:#fff;font-size:11px;font-weight:700;">`)
//line views/ybs/base.qtpl:650
			qw422016.N().D(p.ReplyReviewNum)
//line views/ybs/base.qtpl:650
			qw422016.N().S(`</span>
            </a>
        </li>
        `)
//line views/ybs/base.qtpl:653
		}
//line views/ybs/base.qtpl:653
		qw422016.N().S(`
    </ul>
</div>
`)
//line views/ybs/base.qtpl:656
	}
//line views/ybs/base.qtpl:656
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:658
	if len(p.RecentComment) > 0 {
//line views/ybs/base.qtpl:658
		qw422016.N().S(`
<nav>
    <h4 class="wk-toc-title">最近评论</h4>
    <ul class="wk-recent-comments">
        `)
//line views/ybs/base.qtpl:662
		for k := range p.RecentComment {
//line views/ybs/base.qtpl:662
			qw422016.N().S(`
        <li>
            <img src="/avatar/`)
//line views/ybs/base.qtpl:664
			qw422016.N().DUL(p.RecentComment[k].UserId)
//line views/ybs/base.qtpl:664
			qw422016.N().S(`.jpg" alt="`)
//line views/ybs/base.qtpl:664
			qw422016.E().S(p.RecentComment[k].Name)
//line views/ybs/base.qtpl:664
			qw422016.N().S(` avatar" loading="lazy">
            <a href="`)
//line views/ybs/base.qtpl:665
			qw422016.E().S(p.RecentComment[k].Link)
//line views/ybs/base.qtpl:665
			qw422016.N().S(`">`)
//line views/ybs/base.qtpl:665
			qw422016.E().S(p.RecentComment[k].Content)
//line views/ybs/base.qtpl:665
			qw422016.N().S(`</a>
        </li>
        `)
//line views/ybs/base.qtpl:667
		}
//line views/ybs/base.qtpl:667
		qw422016.N().S(`
    </ul>
</nav>
`)
//line views/ybs/base.qtpl:670
	}
//line views/ybs/base.qtpl:670
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:672
	if p.SiteInfo.NodeNum > 0 {
//line views/ybs/base.qtpl:672
		qw422016.N().S(`
<div class="wk-info-card" style="margin-top:22px;">
    <h4>站点概览</h4>
    <div class="wk-info-row"><span class="k">运行</span><span class="v">`)
//line views/ybs/base.qtpl:675
		qw422016.E().S(p.SiteInfo.Days)
//line views/ybs/base.qtpl:675
		qw422016.N().S(`</span></div>
    <div class="wk-info-row"><span class="k">帖子</span><span class="v"><b>`)
//line views/ybs/base.qtpl:676
		qw422016.N().DUL(p.SiteInfo.PostNum)
//line views/ybs/base.qtpl:676
		qw422016.N().S(`</b></span></div>
    <div class="wk-info-row"><span class="k">回复</span><span class="v"><b>`)
//line views/ybs/base.qtpl:677
		qw422016.N().DUL(p.SiteInfo.ReplyNum)
//line views/ybs/base.qtpl:677
		qw422016.N().S(`</b></span></div>
    <div class="wk-info-row"><span class="k">会员</span><span class="v"><b>`)
//line views/ybs/base.qtpl:678
		qw422016.N().DUL(p.SiteInfo.UserNum)
//line views/ybs/base.qtpl:678
		qw422016.N().S(`</b></span></div>
    <div class="wk-info-row"><span class="k">分类</span><span class="v">`)
//line views/ybs/base.qtpl:679
		qw422016.N().DUL(p.SiteInfo.NodeNum)
//line views/ybs/base.qtpl:679
		qw422016.N().S(`</span></div>
    <div class="wk-info-row"><span class="k">标签</span><span class="v">`)
//line views/ybs/base.qtpl:680
		qw422016.N().DUL(p.SiteInfo.TagNum)
//line views/ybs/base.qtpl:680
		qw422016.N().S(`</span></div>
</div>
`)
//line views/ybs/base.qtpl:682
	}
//line views/ybs/base.qtpl:682
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:684
	if len(p.LinkLst) > 0 {
//line views/ybs/base.qtpl:684
		qw422016.N().S(`
<nav style="margin-top:22px;">
    <h4 class="wk-toc-title">友情链接</h4>
    <ul class="wk-links">
        `)
//line views/ybs/base.qtpl:688
		for k := range p.LinkLst {
//line views/ybs/base.qtpl:688
			qw422016.N().S(`
        <li><a href="`)
//line views/ybs/base.qtpl:689
			qw422016.E().S(p.LinkLst[k].Url)
//line views/ybs/base.qtpl:689
			qw422016.N().S(`" target="_blank" rel="noopener">`)
//line views/ybs/base.qtpl:689
			qw422016.E().S(p.LinkLst[k].Name)
//line views/ybs/base.qtpl:689
			qw422016.N().S(`</a></li>
        `)
//line views/ybs/base.qtpl:690
		}
//line views/ybs/base.qtpl:690
		qw422016.N().S(`
    </ul>
</nav>
`)
//line views/ybs/base.qtpl:693
	}
//line views/ybs/base.qtpl:693
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:694
}

//line views/ybs/base.qtpl:694
func (p *BasePage) WriteAside(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:694
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:694
	p.StreamAside(qw422016)
//line views/ybs/base.qtpl:694
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:694
}

//line views/ybs/base.qtpl:694
func (p *BasePage) Aside() string {
//line views/ybs/base.qtpl:694
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:694
	p.WriteAside(qb422016)
//line views/ybs/base.qtpl:694
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:694
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:694
	return qs422016
//line views/ybs/base.qtpl:694
}

//line views/ybs/base.qtpl:697
func (p *BasePage) StreamFooter(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:697
	qw422016.N().S(`
<p>
    Copyright &copy; <a href="/">`)
//line views/ybs/base.qtpl:699
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:699
	qw422016.N().S(`</a> · Powered by <a href="https://youbbs.org">goYouBBS</a>
</p>
`)
//line views/ybs/base.qtpl:701
	if len(p.SiteCf.FooterPartHtml) > 0 {
//line views/ybs/base.qtpl:701
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:702
		qw422016.N().S(p.SiteCf.FooterPartHtml)
//line views/ybs/base.qtpl:702
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:703
	}
//line views/ybs/base.qtpl:703
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:704
}

//line views/ybs/base.qtpl:704
func (p *BasePage) WriteFooter(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:704
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:704
	p.StreamFooter(qw422016)
//line views/ybs/base.qtpl:704
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:704
}

//line views/ybs/base.qtpl:704
func (p *BasePage) Footer() string {
//line views/ybs/base.qtpl:704
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:704
	p.WriteFooter(qb422016)
//line views/ybs/base.qtpl:704
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:704
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:704
	return qs422016
//line views/ybs/base.qtpl:704
}
