// Code generated by qtc from "home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ybs/home.qtpl:1
package ybs

//line views/ybs/home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/home.qtpl:1
func (p *HomePage) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/home.qtpl:1
	qw422016.N().S(`

<div class="index">

    `)
//line views/ybs/home.qtpl:5
	for _, item := range p.TopicPageInfo.Items {
//line views/ybs/home.qtpl:5
		qw422016.N().S(`
    <article>

        <header>
            `)
//line views/ybs/home.qtpl:9
		if item.Comments > 0 {
//line views/ybs/home.qtpl:9
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/home.qtpl:10
			qw422016.N().DUL(item.ID)
//line views/ybs/home.qtpl:10
			qw422016.N().S(`#r`)
//line views/ybs/home.qtpl:10
			qw422016.N().DUL(item.Comments)
//line views/ybs/home.qtpl:10
			qw422016.N().S(`"><img alt="`)
//line views/ybs/home.qtpl:10
			qw422016.E().S(item.Title)
//line views/ybs/home.qtpl:10
			qw422016.N().S(` icon" src="/icon/t/`)
//line views/ybs/home.qtpl:10
			qw422016.N().DUL(item.ID)
//line views/ybs/home.qtpl:10
			qw422016.N().S(`.jpg?r=`)
//line views/ybs/home.qtpl:10
			qw422016.N().DUL(item.Comments)
//line views/ybs/home.qtpl:10
			qw422016.N().S(`" class="avatar"></a>
            `)
//line views/ybs/home.qtpl:11
		} else {
//line views/ybs/home.qtpl:11
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/home.qtpl:12
			qw422016.N().DUL(item.ID)
//line views/ybs/home.qtpl:12
			qw422016.N().S(`"><img alt="`)
//line views/ybs/home.qtpl:12
			qw422016.E().S(item.Title)
//line views/ybs/home.qtpl:12
			qw422016.N().S(` icon" src="/static/avatar/`)
//line views/ybs/home.qtpl:12
			qw422016.N().DUL(item.UserId)
//line views/ybs/home.qtpl:12
			qw422016.N().S(`.jpg" class="avatar"></a>
            `)
//line views/ybs/home.qtpl:13
		}
//line views/ybs/home.qtpl:13
		qw422016.N().S(`
            <h1><a href="/t/`)
//line views/ybs/home.qtpl:14
		qw422016.N().DUL(item.ID)
//line views/ybs/home.qtpl:14
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line views/ybs/home.qtpl:14
		qw422016.E().S(item.Title)
//line views/ybs/home.qtpl:14
		qw422016.N().S(`">`)
//line views/ybs/home.qtpl:14
		qw422016.E().S(item.Title)
//line views/ybs/home.qtpl:14
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line views/ybs/home.qtpl:16
		qw422016.N().DUL(item.NodeId)
//line views/ybs/home.qtpl:16
		qw422016.N().S(`">`)
//line views/ybs/home.qtpl:16
		qw422016.E().S(item.NodeName)
//line views/ybs/home.qtpl:16
		qw422016.N().S(`</a>
                <a href="/member/`)
//line views/ybs/home.qtpl:17
		qw422016.N().DUL(item.UserId)
//line views/ybs/home.qtpl:17
		qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/home.qtpl:17
		qw422016.E().S(item.AuthorName)
//line views/ybs/home.qtpl:17
		qw422016.N().S(`</a>
                <time datetime="`)
//line views/ybs/home.qtpl:18
		qw422016.E().S(item.AddTimeFmt)
//line views/ybs/home.qtpl:18
		qw422016.N().S(`" pubdate data-updated="true">`)
//line views/ybs/home.qtpl:18
		qw422016.E().S(item.EditTimeFmt)
//line views/ybs/home.qtpl:18
		qw422016.N().S(`</time>
                `)
//line views/ybs/home.qtpl:19
		if item.Comments > 0 {
//line views/ybs/home.qtpl:19
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line views/ybs/home.qtpl:20
			qw422016.N().DUL(item.ID)
//line views/ybs/home.qtpl:20
			qw422016.N().S(`#r`)
//line views/ybs/home.qtpl:20
			qw422016.N().DUL(item.Comments)
//line views/ybs/home.qtpl:20
			qw422016.N().S(`" title="Comment on `)
//line views/ybs/home.qtpl:20
			qw422016.E().S(item.Title)
//line views/ybs/home.qtpl:20
			qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/home.qtpl:20
			qw422016.N().DUL(item.Comments)
//line views/ybs/home.qtpl:20
			qw422016.N().S(`</a>
                `)
//line views/ybs/home.qtpl:21
		}
//line views/ybs/home.qtpl:21
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line views/ybs/home.qtpl:27
	}
//line views/ybs/home.qtpl:27
	qw422016.N().S(`

    <div class="pagination">
        `)
//line views/ybs/home.qtpl:30
	if p.TopicPageInfo.HasPrev {
//line views/ybs/home.qtpl:30
		qw422016.N().S(`
        <a class="prev" href="/?btn=prev&key=`)
//line views/ybs/home.qtpl:31
		qw422016.N().DUL(p.TopicPageInfo.FirstKey)
//line views/ybs/home.qtpl:31
		qw422016.N().S(`&score=`)
//line views/ybs/home.qtpl:31
		qw422016.N().DUL(p.TopicPageInfo.FirstScore)
//line views/ybs/home.qtpl:31
		qw422016.N().S(`">← Newer</a>
        `)
//line views/ybs/home.qtpl:32
	}
//line views/ybs/home.qtpl:32
	qw422016.N().S(`
        `)
//line views/ybs/home.qtpl:33
	if p.TopicPageInfo.HasNext {
//line views/ybs/home.qtpl:33
		qw422016.N().S(`
        <a class="next" href="/?btn=next&key=`)
//line views/ybs/home.qtpl:34
		qw422016.N().DUL(p.TopicPageInfo.LastKey)
//line views/ybs/home.qtpl:34
		qw422016.N().S(`&score=`)
//line views/ybs/home.qtpl:34
		qw422016.N().DUL(p.TopicPageInfo.LastScore)
//line views/ybs/home.qtpl:34
		qw422016.N().S(`">Older →</a>
        `)
//line views/ybs/home.qtpl:35
	}
//line views/ybs/home.qtpl:35
	qw422016.N().S(`
    </div>

</div>

`)
//line views/ybs/home.qtpl:40
}

//line views/ybs/home.qtpl:40
func (p *HomePage) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/home.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/home.qtpl:40
	p.StreamMainBody(qw422016)
//line views/ybs/home.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/home.qtpl:40
}

//line views/ybs/home.qtpl:40
func (p *HomePage) MainBody() string {
//line views/ybs/home.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/home.qtpl:40
	p.WriteMainBody(qb422016)
//line views/ybs/home.qtpl:40
	qs422016 := string(qb422016.B)
//line views/ybs/home.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/home.qtpl:40
	return qs422016
//line views/ybs/home.qtpl:40
}
