// Code generated by qtc from "member.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ybs/member.qtpl:1
package ybs

//line views/ybs/member.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/member.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/member.qtpl:1
func (p *MemberPage) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/member.qtpl:1
	qw422016.N().S(`

<div class="index">
    <div class="user-detail bot-line">
        <img src="/static/avatar/`)
//line views/ybs/member.qtpl:5
	qw422016.N().DUL(p.UserFmt.ID)
//line views/ybs/member.qtpl:5
	qw422016.N().S(`.jpg" alt="`)
//line views/ybs/member.qtpl:5
	qw422016.E().S(p.UserFmt.Name)
//line views/ybs/member.qtpl:5
	qw422016.N().S(` avatar" class="avatar right" >
        <h1>
        会员: `)
//line views/ybs/member.qtpl:7
	qw422016.E().S(p.UserFmt.Name)
//line views/ybs/member.qtpl:7
	qw422016.N().S(`
        `)
//line views/ybs/member.qtpl:8
	if p.CurrentUser.Flag >= 99 {
//line views/ybs/member.qtpl:8
		qw422016.N().S(`
        - <a href="/admin/user?id=`)
//line views/ybs/member.qtpl:9
		qw422016.N().DUL(p.UserFmt.ID)
//line views/ybs/member.qtpl:9
		qw422016.N().S(`">Edit</a>
        `)
//line views/ybs/member.qtpl:10
	}
//line views/ybs/member.qtpl:10
	qw422016.N().S(`
        </h1>
        <ul class="user-info">
            <li>注册时间： `)
//line views/ybs/member.qtpl:13
	qw422016.E().S(p.UserFmt.RegTimeFmt)
//line views/ybs/member.qtpl:13
	qw422016.N().S(`</li>
            <li>Web: <a href="`)
//line views/ybs/member.qtpl:14
	qw422016.E().S(p.UserFmt.Url)
//line views/ybs/member.qtpl:14
	qw422016.N().S(`" target="_blank">`)
//line views/ybs/member.qtpl:14
	qw422016.E().S(p.UserFmt.Url)
//line views/ybs/member.qtpl:14
	qw422016.N().S(`</a></li>
            <li>About: `)
//line views/ybs/member.qtpl:15
	qw422016.E().S(p.UserFmt.About)
//line views/ybs/member.qtpl:15
	qw422016.N().S(`</li>
        </ul>
        <div class="pure-button-group">
            <a class="pure-button `)
//line views/ybs/member.qtpl:18
	if p.LstType == "topic" {
//line views/ybs/member.qtpl:18
		qw422016.N().S(`pure-button-active`)
//line views/ybs/member.qtpl:18
	}
//line views/ybs/member.qtpl:18
	qw422016.N().S(`" href="?type=topic">主题</a>
            <a class="pure-button `)
//line views/ybs/member.qtpl:19
	if p.LstType == "comment" {
//line views/ybs/member.qtpl:19
		qw422016.N().S(`pure-button-active`)
//line views/ybs/member.qtpl:19
	}
//line views/ybs/member.qtpl:19
	qw422016.N().S(`" href="?type=comment">评论</a>
        </div>
    </div>

    `)
//line views/ybs/member.qtpl:23
	if len(p.TopicLst) > 0 {
//line views/ybs/member.qtpl:23
		qw422016.N().S(`
    <h2 class="bot-line">待审核主题</h2>
    <ul class="bot-line">
        `)
//line views/ybs/member.qtpl:26
		for _, item := range p.TopicLst {
//line views/ybs/member.qtpl:26
			qw422016.N().S(`
        <li>
            [`)
//line views/ybs/member.qtpl:28
			qw422016.E().S(item.AddTimeFmt)
//line views/ybs/member.qtpl:28
			qw422016.N().S(`] `)
//line views/ybs/member.qtpl:28
			qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:28
			qw422016.N().S(` <br>&nbsp;
        </li>
        `)
//line views/ybs/member.qtpl:30
		}
//line views/ybs/member.qtpl:30
		qw422016.N().S(`
    </ul>
    `)
//line views/ybs/member.qtpl:32
	}
//line views/ybs/member.qtpl:32
	qw422016.N().S(`

    `)
//line views/ybs/member.qtpl:34
	if len(p.CommentReviewLst) > 0 {
//line views/ybs/member.qtpl:34
		qw422016.N().S(`
    <h2 class="bot-line">待审核评论</h2>
    <ul class="bot-line">
        `)
//line views/ybs/member.qtpl:37
		for _, item := range p.CommentReviewLst {
//line views/ybs/member.qtpl:37
			qw422016.N().S(`
        <li>
            主题: <a href="/t/`)
//line views/ybs/member.qtpl:39
			qw422016.N().DUL(item.TopicId)
//line views/ybs/member.qtpl:39
			qw422016.N().S(`">`)
//line views/ybs/member.qtpl:39
			qw422016.E().S(item.TopicTitle)
//line views/ybs/member.qtpl:39
			qw422016.N().S(`</a><br>
            <div class="gray">`)
//line views/ybs/member.qtpl:40
			qw422016.E().S(item.AddTimeFmt)
//line views/ybs/member.qtpl:40
			qw422016.N().S(`</div>
            <div class="markdown-body entry-content">
                `)
//line views/ybs/member.qtpl:42
			qw422016.N().S(item.ContentFmt)
//line views/ybs/member.qtpl:42
			qw422016.N().S(`
            </div>
        </li>
        `)
//line views/ybs/member.qtpl:45
		}
//line views/ybs/member.qtpl:45
		qw422016.N().S(`
    </ul>
    `)
//line views/ybs/member.qtpl:47
	}
//line views/ybs/member.qtpl:47
	qw422016.N().S(`

    `)
//line views/ybs/member.qtpl:49
	for _, item := range p.TopicPageInfo.Items {
//line views/ybs/member.qtpl:49
		qw422016.N().S(`
    <article>

        <header>
            `)
//line views/ybs/member.qtpl:53
		if item.Comments > 0 {
//line views/ybs/member.qtpl:53
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/member.qtpl:54
			qw422016.N().DUL(item.ID)
//line views/ybs/member.qtpl:54
			qw422016.N().S(`#r`)
//line views/ybs/member.qtpl:54
			qw422016.N().DUL(item.Comments)
//line views/ybs/member.qtpl:54
			qw422016.N().S(`"><img alt="`)
//line views/ybs/member.qtpl:54
			qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:54
			qw422016.N().S(` icon" src="/icon/t/`)
//line views/ybs/member.qtpl:54
			qw422016.N().DUL(item.ID)
//line views/ybs/member.qtpl:54
			qw422016.N().S(`.jpg?r=`)
//line views/ybs/member.qtpl:54
			qw422016.N().DUL(item.Comments)
//line views/ybs/member.qtpl:54
			qw422016.N().S(`" class="avatar"></a>
            `)
//line views/ybs/member.qtpl:55
		} else {
//line views/ybs/member.qtpl:55
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/member.qtpl:56
			qw422016.N().DUL(item.ID)
//line views/ybs/member.qtpl:56
			qw422016.N().S(`"><img alt="`)
//line views/ybs/member.qtpl:56
			qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:56
			qw422016.N().S(` icon" src="/static/avatar/`)
//line views/ybs/member.qtpl:56
			qw422016.N().DUL(item.UserId)
//line views/ybs/member.qtpl:56
			qw422016.N().S(`.jpg" class="avatar"></a>
            `)
//line views/ybs/member.qtpl:57
		}
//line views/ybs/member.qtpl:57
		qw422016.N().S(`
            <h1><a href="/t/`)
//line views/ybs/member.qtpl:58
		qw422016.N().DUL(item.ID)
//line views/ybs/member.qtpl:58
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line views/ybs/member.qtpl:58
		qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:58
		qw422016.N().S(`">`)
//line views/ybs/member.qtpl:58
		qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:58
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line views/ybs/member.qtpl:60
		qw422016.N().DUL(item.NodeId)
//line views/ybs/member.qtpl:60
		qw422016.N().S(`">`)
//line views/ybs/member.qtpl:60
		qw422016.E().S(item.NodeName)
//line views/ybs/member.qtpl:60
		qw422016.N().S(`</a>
                <a href="/member/`)
//line views/ybs/member.qtpl:61
		qw422016.N().DUL(item.UserId)
//line views/ybs/member.qtpl:61
		qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/member.qtpl:61
		qw422016.E().S(item.AuthorName)
//line views/ybs/member.qtpl:61
		qw422016.N().S(`</a>
                <time datetime="`)
//line views/ybs/member.qtpl:62
		qw422016.E().S(item.AddTimeFmt)
//line views/ybs/member.qtpl:62
		qw422016.N().S(`" pubdate data-updated="true">`)
//line views/ybs/member.qtpl:62
		qw422016.E().S(item.EditTimeFmt)
//line views/ybs/member.qtpl:62
		qw422016.N().S(`</time>
                `)
//line views/ybs/member.qtpl:63
		if item.Comments > 0 {
//line views/ybs/member.qtpl:63
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line views/ybs/member.qtpl:64
			qw422016.N().DUL(item.ID)
//line views/ybs/member.qtpl:64
			qw422016.N().S(`#r`)
//line views/ybs/member.qtpl:64
			qw422016.N().DUL(item.Comments)
//line views/ybs/member.qtpl:64
			qw422016.N().S(`" title="Comment on `)
//line views/ybs/member.qtpl:64
			qw422016.E().S(item.Title)
//line views/ybs/member.qtpl:64
			qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/member.qtpl:64
			qw422016.N().DUL(item.Comments)
//line views/ybs/member.qtpl:64
			qw422016.N().S(`</a>
                `)
//line views/ybs/member.qtpl:65
		}
//line views/ybs/member.qtpl:65
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line views/ybs/member.qtpl:71
	}
//line views/ybs/member.qtpl:71
	qw422016.N().S(`

    <div class="pagination">
        `)
//line views/ybs/member.qtpl:74
	if p.TopicPageInfo.HasPrev {
//line views/ybs/member.qtpl:74
		qw422016.N().S(`
        <a class="prev" href="?type=`)
//line views/ybs/member.qtpl:75
		qw422016.E().S(p.LstType)
//line views/ybs/member.qtpl:75
		qw422016.N().S(`&btn=prev&key=`)
//line views/ybs/member.qtpl:75
		qw422016.N().DUL(p.TopicPageInfo.FirstKey)
//line views/ybs/member.qtpl:75
		qw422016.N().S(`&score=`)
//line views/ybs/member.qtpl:75
		qw422016.N().DUL(p.TopicPageInfo.FirstScore)
//line views/ybs/member.qtpl:75
		qw422016.N().S(`">← Newer</a>
        `)
//line views/ybs/member.qtpl:76
	}
//line views/ybs/member.qtpl:76
	qw422016.N().S(`
        `)
//line views/ybs/member.qtpl:77
	if p.TopicPageInfo.HasNext {
//line views/ybs/member.qtpl:77
		qw422016.N().S(`
        <a class="next" href="?type=`)
//line views/ybs/member.qtpl:78
		qw422016.E().S(p.LstType)
//line views/ybs/member.qtpl:78
		qw422016.N().S(`&btn=next&key=`)
//line views/ybs/member.qtpl:78
		qw422016.N().DUL(p.TopicPageInfo.LastKey)
//line views/ybs/member.qtpl:78
		qw422016.N().S(`&score=`)
//line views/ybs/member.qtpl:78
		qw422016.N().DUL(p.TopicPageInfo.LastScore)
//line views/ybs/member.qtpl:78
		qw422016.N().S(`">Older →</a>
        `)
//line views/ybs/member.qtpl:79
	}
//line views/ybs/member.qtpl:79
	qw422016.N().S(`
    </div>

</div>

`)
//line views/ybs/member.qtpl:84
}

//line views/ybs/member.qtpl:84
func (p *MemberPage) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/member.qtpl:84
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/member.qtpl:84
	p.StreamMainBody(qw422016)
//line views/ybs/member.qtpl:84
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/member.qtpl:84
}

//line views/ybs/member.qtpl:84
func (p *MemberPage) MainBody() string {
//line views/ybs/member.qtpl:84
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/member.qtpl:84
	p.WriteMainBody(qb422016)
//line views/ybs/member.qtpl:84
	qs422016 := string(qb422016.B)
//line views/ybs/member.qtpl:84
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/member.qtpl:84
	return qs422016
//line views/ybs/member.qtpl:84
}
