// Code generated by qtc from "tag.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ybs/tag.qtpl:1
package ybs

//line views/ybs/tag.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/tag.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/tag.qtpl:1
func (p *TagPage) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/tag.qtpl:1
	qw422016.N().S(`
<div class="index">

    <header class="bot-line">
        <h1 class="entry-title">Tag: `)
//line views/ybs/tag.qtpl:5
	qw422016.E().S(p.Tag)
//line views/ybs/tag.qtpl:5
	qw422016.N().S(`</h1>
    </header>

    `)
//line views/ybs/tag.qtpl:8
	for _, item := range p.TopicPageInfo.Items {
//line views/ybs/tag.qtpl:8
		qw422016.N().S(`
    <article>

        <header>
            `)
//line views/ybs/tag.qtpl:12
		if item.Comments > 0 {
//line views/ybs/tag.qtpl:12
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/tag.qtpl:13
			qw422016.N().DUL(item.ID)
//line views/ybs/tag.qtpl:13
			qw422016.N().S(`#r`)
//line views/ybs/tag.qtpl:13
			qw422016.N().DUL(item.Comments)
//line views/ybs/tag.qtpl:13
			qw422016.N().S(`"><img alt="`)
//line views/ybs/tag.qtpl:13
			qw422016.E().S(item.Title)
//line views/ybs/tag.qtpl:13
			qw422016.N().S(` icon" src="/icon/t/`)
//line views/ybs/tag.qtpl:13
			qw422016.N().DUL(item.ID)
//line views/ybs/tag.qtpl:13
			qw422016.N().S(`.jpg?r=`)
//line views/ybs/tag.qtpl:13
			qw422016.N().DUL(item.Comments)
//line views/ybs/tag.qtpl:13
			qw422016.N().S(`" class="avatar"></a>
            `)
//line views/ybs/tag.qtpl:14
		} else {
//line views/ybs/tag.qtpl:14
			qw422016.N().S(`
            <a href="/t/`)
//line views/ybs/tag.qtpl:15
			qw422016.N().DUL(item.ID)
//line views/ybs/tag.qtpl:15
			qw422016.N().S(`"><img alt="`)
//line views/ybs/tag.qtpl:15
			qw422016.E().S(item.Title)
//line views/ybs/tag.qtpl:15
			qw422016.N().S(` icon" src="/static/avatar/`)
//line views/ybs/tag.qtpl:15
			qw422016.N().DUL(item.UserId)
//line views/ybs/tag.qtpl:15
			qw422016.N().S(`.jpg" class="avatar"></a>
            `)
//line views/ybs/tag.qtpl:16
		}
//line views/ybs/tag.qtpl:16
		qw422016.N().S(`
            <h1><a href="/t/`)
//line views/ybs/tag.qtpl:17
		qw422016.N().DUL(item.ID)
//line views/ybs/tag.qtpl:17
		qw422016.N().S(`" rel="bookmark" title="Permanent Link to `)
//line views/ybs/tag.qtpl:17
		qw422016.E().S(item.Title)
//line views/ybs/tag.qtpl:17
		qw422016.N().S(`">`)
//line views/ybs/tag.qtpl:17
		qw422016.E().S(item.Title)
//line views/ybs/tag.qtpl:17
		qw422016.N().S(`</a></h1>
            <p class="meta">
                <a href="/n/`)
//line views/ybs/tag.qtpl:19
		qw422016.N().DUL(item.NodeId)
//line views/ybs/tag.qtpl:19
		qw422016.N().S(`">`)
//line views/ybs/tag.qtpl:19
		qw422016.E().S(item.NodeName)
//line views/ybs/tag.qtpl:19
		qw422016.N().S(`</a>
                <a href="/member/`)
//line views/ybs/tag.qtpl:20
		qw422016.N().DUL(item.UserId)
//line views/ybs/tag.qtpl:20
		qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/tag.qtpl:20
		qw422016.E().S(item.AuthorName)
//line views/ybs/tag.qtpl:20
		qw422016.N().S(`</a>
                <time datetime="`)
//line views/ybs/tag.qtpl:21
		qw422016.E().S(item.AddTimeFmt)
//line views/ybs/tag.qtpl:21
		qw422016.N().S(`" pubdate data-updated="true">`)
//line views/ybs/tag.qtpl:21
		qw422016.E().S(item.EditTimeFmt)
//line views/ybs/tag.qtpl:21
		qw422016.N().S(`</time>
                `)
//line views/ybs/tag.qtpl:22
		if item.Comments > 0 {
//line views/ybs/tag.qtpl:22
			qw422016.N().S(`
                <a class="right count" href="/t/`)
//line views/ybs/tag.qtpl:23
			qw422016.N().DUL(item.ID)
//line views/ybs/tag.qtpl:23
			qw422016.N().S(`#r`)
//line views/ybs/tag.qtpl:23
			qw422016.N().DUL(item.Comments)
//line views/ybs/tag.qtpl:23
			qw422016.N().S(`" title="Comment on `)
//line views/ybs/tag.qtpl:23
			qw422016.E().S(item.Title)
//line views/ybs/tag.qtpl:23
			qw422016.N().S(`" rel="nofollow">`)
//line views/ybs/tag.qtpl:23
			qw422016.N().DUL(item.Comments)
//line views/ybs/tag.qtpl:23
			qw422016.N().S(`</a>
                `)
//line views/ybs/tag.qtpl:24
		}
//line views/ybs/tag.qtpl:24
		qw422016.N().S(`
            </p>
        </header>

    </article>

    `)
//line views/ybs/tag.qtpl:30
	}
//line views/ybs/tag.qtpl:30
	qw422016.N().S(`

    <div class="pagination">
        `)
//line views/ybs/tag.qtpl:33
	if p.TopicPageInfo.HasPrev {
//line views/ybs/tag.qtpl:33
		qw422016.N().S(`
        <a class="prev" href="/tag/`)
//line views/ybs/tag.qtpl:34
		qw422016.E().S(p.Tag)
//line views/ybs/tag.qtpl:34
		qw422016.N().S(`?btn=prev&key=`)
//line views/ybs/tag.qtpl:34
		qw422016.N().DUL(p.TopicPageInfo.FirstKey)
//line views/ybs/tag.qtpl:34
		qw422016.N().S(`&score=`)
//line views/ybs/tag.qtpl:34
		qw422016.N().DUL(p.TopicPageInfo.FirstScore)
//line views/ybs/tag.qtpl:34
		qw422016.N().S(`">← Newer</a>
        `)
//line views/ybs/tag.qtpl:35
	}
//line views/ybs/tag.qtpl:35
	qw422016.N().S(`
        `)
//line views/ybs/tag.qtpl:36
	if p.TopicPageInfo.HasNext {
//line views/ybs/tag.qtpl:36
		qw422016.N().S(`
        <a class="next" href="/tag/`)
//line views/ybs/tag.qtpl:37
		qw422016.E().S(p.Tag)
//line views/ybs/tag.qtpl:37
		qw422016.N().S(`?btn=next&key=`)
//line views/ybs/tag.qtpl:37
		qw422016.N().DUL(p.TopicPageInfo.LastKey)
//line views/ybs/tag.qtpl:37
		qw422016.N().S(`&score=`)
//line views/ybs/tag.qtpl:37
		qw422016.N().DUL(p.TopicPageInfo.LastScore)
//line views/ybs/tag.qtpl:37
		qw422016.N().S(`">Older →</a>
        `)
//line views/ybs/tag.qtpl:38
	}
//line views/ybs/tag.qtpl:38
	qw422016.N().S(`
    </div>

</div>
`)
//line views/ybs/tag.qtpl:42
}

//line views/ybs/tag.qtpl:42
func (p *TagPage) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/tag.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/tag.qtpl:42
	p.StreamMainBody(qw422016)
//line views/ybs/tag.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/tag.qtpl:42
}

//line views/ybs/tag.qtpl:42
func (p *TagPage) MainBody() string {
//line views/ybs/tag.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/tag.qtpl:42
	p.WriteMainBody(qb422016)
//line views/ybs/tag.qtpl:42
	qs422016 := string(qb422016.B)
//line views/ybs/tag.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/tag.qtpl:42
	return qs422016
//line views/ybs/tag.qtpl:42
}
