// Code generated by qtc from "user_loginnregister.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/ybs/user_loginnregister.qtpl:1
package ybs

//line views/ybs/user_loginnregister.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/user_loginnregister.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/user_loginnregister.qtpl:1
func (p *UserLogin) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/user_loginnregister.qtpl:1
	qw422016.N().S(`
<script src="/static/js/md5.min.js" type="text/javascript"></script>
<div class="index">
    <header class="bot-line">
        <h1 class="entry-title">`)
//line views/ybs/user_loginnregister.qtpl:5
	qw422016.E().S(p.Title)
//line views/ybs/user_loginnregister.qtpl:5
	qw422016.N().S(`</h1>
    </header>
    <h2>账号密码 - `)
//line views/ybs/user_loginnregister.qtpl:7
	qw422016.E().S(p.Title)
//line views/ybs/user_loginnregister.qtpl:7
	qw422016.N().S(`</h2>
    <form class="pure-form pure-form-aligned" action="" method="post" onsubmit="form_post(); return false;">
        <fieldset>
            <div class="pure-control-group">
                <label for="name">登录名： </label>
                <input id="name" type="text" value="`)
//line views/ybs/user_loginnregister.qtpl:12
	qw422016.E().S(p.DefaultName)
//line views/ybs/user_loginnregister.qtpl:12
	qw422016.N().S(`" autocomplete="off" autofocus>
            </div>

            <div class="pure-control-group">
                <label for="password">密　码： </label>
                <input id="password" type="password">
            </div>

            `)
//line views/ybs/user_loginnregister.qtpl:20
	if p.Act == "register" {
//line views/ybs/user_loginnregister.qtpl:20
		qw422016.N().S(`
            <div class="pure-control-group">
                <label for="password">重　复： </label>
                <input id="password2" type="password">
            </div>
            `)
//line views/ybs/user_loginnregister.qtpl:25
	} else {
//line views/ybs/user_loginnregister.qtpl:25
		qw422016.N().S(`
            <input id="password2" type="hidden" value="">
            `)
//line views/ybs/user_loginnregister.qtpl:27
	}
//line views/ybs/user_loginnregister.qtpl:27
	qw422016.N().S(`

            <div class="pure-control-group">
                <label for="image"></label>
                <span class="pure-form-message-inline"><img id="image" onclick="reload()" src="/captcha/`)
//line views/ybs/user_loginnregister.qtpl:31
	qw422016.E().S(p.CaptchaId)
//line views/ybs/user_loginnregister.qtpl:31
	qw422016.N().S(`.png" alt="Captcha image"></span>
            </div>

            <div class="pure-control-group">
                <label for="captchaSolution">验证码： </label>
                <input id="captchaSolution" type="number">
            </div>

            <div class="pure-controls">
                <span id="id-msg"></span>
                <button type="submit" id="submit" class="pure-button pure-button-primary"> `)
//line views/ybs/user_loginnregister.qtpl:41
	qw422016.E().S(p.Title)
//line views/ybs/user_loginnregister.qtpl:41
	qw422016.N().S(` </button>
            </div>
        </fieldset>
    </form>

    `)
//line views/ybs/user_loginnregister.qtpl:46
	if p.HasOtherAuth {
//line views/ybs/user_loginnregister.qtpl:46
		qw422016.N().S(`
    <h2>其它登录方式</h2>
    `)
//line views/ybs/user_loginnregister.qtpl:48
		if p.SiteCf.QQClientID != "" {
//line views/ybs/user_loginnregister.qtpl:48
			qw422016.N().S(`
    <a href="/qqlogin" rel="nofollow"><img src="/static/images/icon_qq_64.png" alt="QQ登录" class="avatar"></a>
    `)
//line views/ybs/user_loginnregister.qtpl:50
		}
//line views/ybs/user_loginnregister.qtpl:50
		qw422016.N().S(`
    `)
//line views/ybs/user_loginnregister.qtpl:51
		if p.SiteCf.WeiboClientID != "" {
//line views/ybs/user_loginnregister.qtpl:51
			qw422016.N().S(`
    <a href="/wblogin" rel="nofollow"><img src="/static/images/icon_weibo_64.png" alt="微博登录" class="avatar"></a>
    `)
//line views/ybs/user_loginnregister.qtpl:53
		}
//line views/ybs/user_loginnregister.qtpl:53
		qw422016.N().S(`
    `)
//line views/ybs/user_loginnregister.qtpl:54
		if p.SiteCf.GithubClientID != "" {
//line views/ybs/user_loginnregister.qtpl:54
			qw422016.N().S(`
    <a href="/githublogin" rel="nofollow"><img src="/static/images/icon_github_64.png" alt="github登录" class="avatar"></a>
    `)
//line views/ybs/user_loginnregister.qtpl:56
		}
//line views/ybs/user_loginnregister.qtpl:56
		qw422016.N().S(`
    `)
//line views/ybs/user_loginnregister.qtpl:57
	}
//line views/ybs/user_loginnregister.qtpl:57
	qw422016.N().S(`

    <script>
        var captchaId = '`)
//line views/ybs/user_loginnregister.qtpl:60
	qw422016.E().S(p.CaptchaId)
//line views/ybs/user_loginnregister.qtpl:60
	qw422016.N().S(`';
        function setSrcQuery(e, q) {
            var src  = e.src;
            var p = src.indexOf('?');
            if (p >= 0) {
                src = src.substr(0, p);
            }
            e.src = src + "?" + q
        }

        function reload() {
            setSrcQuery(document.getElementById('image'), "reload=" + (new Date()).getTime());
            document.getElementById('captchaSolution').value = "";
            return false;
        }

        function form_post(){
            let msgEle = document.getElementById("id-msg");
            let name = document.getElementById('name').value.trim();
            let password = document.getElementById('password').value.trim();
            let password2 = document.getElementById('password2').value.trim();

            if(password2) {
                if(password !== password2) {
                    msgEle.style.display = "block";
                    msgEle.style.color = "red";
                    msgEle.innerText = "两次输入密码不一样";
                    return false;
                }
            }

            let captchaSolution = document.getElementById('captchaSolution').value.trim();
            if(name && password && captchaSolution){
                msgEle.style.display = "none";
                postAjax("/`)
//line views/ybs/user_loginnregister.qtpl:94
	qw422016.E().S(p.Act)
//line views/ybs/user_loginnregister.qtpl:94
	qw422016.N().S(`", JSON.stringify({'Act': '`)
//line views/ybs/user_loginnregister.qtpl:94
	qw422016.E().S(p.Act)
//line views/ybs/user_loginnregister.qtpl:94
	qw422016.N().S(`', 'Name': name, 'Password': md5(password), 'CaptchaSolution': captchaSolution, 'CaptchaId': captchaId}), function(data){
                    let obj = JSON.parse(data)
                    //console.log(obj);
                    if(obj.Code === 200) {
                        window.location.href = "/";
                        return false;
                    } else {
                        msgEle.style.display = "block";
                        msgEle.style.color = "red";
                        msgEle.innerText = obj.Msg;
                        if (obj.Code === 405) {
                            document.getElementById('image').src = "/captcha/"+obj.NewCaptchaId+".png";
                            captchaId = obj.NewCaptchaId;
                            document.getElementById('captchaSolution').value = "";
                            return false;
                        }else{
                            reload();
                        }
                    }
                });
            }
            return false;
        }

    </script>

</div>

`)
//line views/ybs/user_loginnregister.qtpl:122
}

//line views/ybs/user_loginnregister.qtpl:122
func (p *UserLogin) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/user_loginnregister.qtpl:122
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/user_loginnregister.qtpl:122
	p.StreamMainBody(qw422016)
//line views/ybs/user_loginnregister.qtpl:122
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/user_loginnregister.qtpl:122
}

//line views/ybs/user_loginnregister.qtpl:122
func (p *UserLogin) MainBody() string {
//line views/ybs/user_loginnregister.qtpl:122
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/user_loginnregister.qtpl:122
	p.WriteMainBody(qb422016)
//line views/ybs/user_loginnregister.qtpl:122
	qs422016 := string(qb422016.B)
//line views/ybs/user_loginnregister.qtpl:122
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/user_loginnregister.qtpl:122
	return qs422016
//line views/ybs/user_loginnregister.qtpl:122
}
